### ISSUE TITLE
Magento 2.2.0 Admin Layout 

### ISSUE THREAD

**Issue by lillik** [magefan/module-blog#100]
Please take a look at Image.
![M2.2.0Admin](http://res.cloudinary.com/dho2b9ukb/image/upload/v1509013879/m2_blog_ernz4k.png)

**Comment by magefan** [comment]
@lillik , we know that our current grids are not built via ui_component, and this change is in our backlog, but now we have other priority, we are working on native comments system.

or maybe I have understand you wrong?
