### ISSUE TITLE
Magento 2.2.0 : TypeError: element.getRecordCount is not a function in dynamic rows in admin form

### ISSUE THREAD

**Issue by makwanaajay** [magefan/module-blog#102]
I have used this blog module for my custom module and created other modules  with Magento 2.1.6 and there is dynamic rows added in custom module form. Where admin can add dynamic data with the help of magento dynamic rows. And It is working fine with that magento version. But when I have integrated that same module in Magento 2.2.0, it is not working and below error occurred.

TypeError: element.getRecordCount is not a function

How can I resolve this issue ?

**Comment by magefan** [comment]
@makwanaajay, We're so sorry, but  I think we cannot help you with this issue. This github issues tracking  only for native blog functionality. 

Try to make debug to figure out the reason of the issue.

P.S.: for Magento 2.2.0 there was no blog extension main core changes.
