### ISSUE TITLE
Featured Image not uploading 

### ISSUE THREAD

**Issue by Tonop** [magefan/module-blog#103]
Hi!

Magento 2.1.9
Magefan Blog 2.5.4

I encountered with issue  that  featured Image not uploading with 2.5.0 version, After upgrading to 2.5.4 it is still present.

Progress bar is always in rotating state. Pls have a look at screenshot.
If you have remote access to check, no problem pls let me know.

BR,
Boris

**Comment by Tonop** [comment]
It looks like the issue appears only in Yandex Browser. Just checked with Chrome - all works! )

**Comment by magefan** [comment]
"

**Comment by magefan** [comment]
@Tonop could you please try to upload image for category (catalog category, not blog category) ?
