### ISSUE TITLE
line heigt post

### ISSUE THREAD

**Issue by MarusaThem** [magefan/module-blog#104]
When i edit line heigt in post for blog. I dont see it is apply when review post. How to edit it? i has tried in Admin but cannot

**Comment by magefan** [comment]
@MarusaThem, please try this:
1. Flush Page Cache (or varnish) after you saved post.
2. Make sure that WYSIWYG editor do not crop your height tag, or style tag (you can check this in database after you saved post)
3. Maybe your theme has some styles that override yours.
