### ISSUE TITLE
Conflict with Cloudflare plugin? Not sure whose issue it is

### ISSUE THREAD

**Issue by ausl** [magefan/module-blog#105]
Hi, see the following error code when cloudflare plugin installed:

[31-Oct-2017 09:02:43 UTC] PHP Fatal error:  Uncaught Error: Call to a member function getId() on null in /home/xxx/public_html/vendor/magefan/module-blog/Block/Catalog/Product/RelatedPosts.php:82
Stack trace:
#0 /home/xxx/public_html/vendor/cloudflare/cloudflare-magento/Model/Layout/LayoutPlugin.php(70): Magefan\Blog\Block\Catalog\Product\RelatedPosts->getIdentities()
#1 /home/xxx/public_html/vendor/magento/framework/Interception/Interceptor.php(146): CloudFlare\Plugin\Model\Layout\LayoutPlugin->afterGetOutput(Object(Magento\Framework\View\Layout\Interceptor), '<div class="sti...')
#2 /home/xxx/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}()
#3 /home/xxx/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(494): Magento\Framework\View\Layout\Interceptor->___callPlugins('getOutput', Array, Array)
#4 /home/xxx/public_html/vendor/magento/framework/View/Result/Page.php(257): Magento\Framework\View\L in /home/xxx/public_html/vendor/magefan/module-blog/Block/Catalog/Product/RelatedPosts.php on line 82

**Comment by magefan** [comment]
Hello @ausl , thank you for your report. I think this is our issue. Please try this fix https://github.com/magefan/module-blog/commit/6c92dc319153d3874633826c386a8ba1c8db68ff
please let us know if it works for you.
