### ISSUE TITLE
Element 'htmlContent': This element is not expected.

### ISSUE THREAD

**Issue by imrankln** [magefan/module-blog#108]
Hello 
after updating yesterday. i am getting following error

Exception #0 (Magento\Framework\Exception\LocalizedException): Element 'htmlContent': This element is not expected. Expected is one of ( field, fieldset, container, dataSource, insertForm, insertListing, modal ).
Line: 329

my version is 2.1.9

**Comment by magefan** [comment]
@imrankln I think you installed pre-released version from master branch. So you have 2 options:
1. Use official release 2.6.1
2. Comment htmlContent section in view/adminhtml/ui_component/blog_post_form.xml (https://github.com/magefan/module-blog/commit/6f6bc3b94e2296fa43f0f6e452c7f760ed207d80)

**Comment by imrankln** [comment]
my current version is 2.6.1

**Comment by magefan** [comment]
Yes, the same version is now in master tag. 

Please use
`composer require magefan/module-blog 2.6.1`
to install official 2.6.1 release. 
or you can download it here
https://github.com/magefan/module-blog/releases/tag/2.6.1

**Comment by imrankln** [comment]
Thank you very much

**Comment by diazwatson** [comment]
I am getting the same issue in 2.6.2. 
I am going to update to 2.7.0 as I see the piece of code is commented out in there.

**Comment by magefan** [comment]
@diazwatson this issue is happens on Magneto2.1.x only so you need to apply this fix https://github.com/magefan/module-blog/commit/f46a813249c884126d747a623a89abfb656f94af or update to blog v2.7.0

**Comment by diazwatson** [comment]
Updated to 2.7.0 and is working again. Thanks

**Comment by magefan** [comment]
Great.

**Comment by cucoriedka** [comment]
I'm getting the same error after updating to the latest version 2.8.7. I've downloaded files from the official website.

Has anyone experienced this problem and has solution to this?

**Comment by cucoriedka** [comment]
> I'm getting the same error after updating to the latest version 2.8.7. I've downloaded files from the official website. My version of Magento is 2.1.5
> 
> Has anyone experienced this problem and has solution to this?

Follow this fix [f46a813](https://github.com/magefan/module-blog/commit/f46a813249c884126d747a623a89abfb656f94af) - comment out htmlContent section in `view/adminhtml/ui_component/blog_post_form.xml` if you're using Magento 2.1 version

**Comment by magefan** [comment]
@cucoriedka , please wait, we have reproduced this issue and now preparing a fix. It will be ready tomorrow.

**Comment by cucoriedka** [comment]
@magefan Thank you for your fast reply! Look forward to your solution.

**Comment by magefan** [comment]
@cucoriedka , please use this fix https://github.com/magefan/module-blog/commit/325f309c4b503100ca32add3e65c5989252696bc
Let us know if it work

**Comment by cucoriedka** [comment]
@magefan Thank you, this fixed worked! :)
