### ISSUE TITLE
Non US locale post saving issue

### ISSUE THREAD

**Issue by fluential** [magefan/module-blog#109]
Hi there I am running latest module version on the UK locale and when trying to edit already made post and save it again, there is a problem:

`
Something went wrong while saving this post. Invalid input date format '23/11/2017'
`
When I leave the date empty (specifically remove its default value) the post save goes fine and date stays unchanged.

When I enter date like 11/23/2017 I get
`
Something went wrong while saving this post. Invalid input date format 'Invalid date'
`

```
Magento ver. 2.1.9
PHP: 7.0.24
Magefan Blog 2.6.1
```

Any more info I could provide?

**Comment by magefan** [comment]
Hello @fluential, I think this issue duplicate this one https://github.com/magefan/module-blog/issues/30
Could you please try to set dates for e.g. in design section for CMS Page? Please let me know if you get the same error there?

**Comment by fluential** [comment]
Hi @magefan actually you may be right it seems it has jus been fixed in Magento 2.2 via https://github.com/magento/magento2/issues/6323
