### ISSUE TITLE
Main Menu dissaper when i enable the Display Blog Link 

### ISSUE THREAD

**Issue by refaelgold** [magefan/module-blog#111]
When i enable the Display Blog Link - the menu is Disappear  . 

I test it on Luma theme on  M 2.2.1

**Comment by magefan** [comment]
What blog version do you use?
We cannot reproduce this issue on M2.2.1 with master branch.
Could you check logs?

**Comment by refaelgold** [comment]
My bad - default.xml not configure correctly.
Top.link was removed accidentally.
