### ISSUE TITLE
Media Gallery is missing (2.6.1)

### ISSUE THREAD

**Issue by Geert82** [magefan/module-blog#112]
**Issue:**
Media Gallery is missing from (Content > BLOG (posts) > Add New Post)

**Steps to reproduce:**
Magento 2.2.1
PHP 7.1.x
Magefan Blog 2.6.1 (updated 2.5.3 -> 2.6.1) 
Redis/Varnish
Add a new blog post and add a media gallery

**Expected result:**
Media Gallery is displayed to add a photo gallery to the post

**Actual result:**
Media Gallery is not showing (Content > BLOG (posts) > Add New Post)
Media Gallery on older posts is displayed correctly on frontend, editing is not possible in the backend.

**Comment by magefan** [comment]
@Geert82, it issue already fixed https://github.com/magefan/module-blog/commit/6f6bc3b94e2296fa43f0f6e452c7f760ed207d80. This fix will be included in next release.
