### ISSUE TITLE
Cache language issue

### ISSUE THREAD

**Issue by Krupaly2k** [magefan/module-blog#113]
Hi,

I have nl as default language of the website. After installing this extension whenever I am clearing cache it creates cache folder en_US. So, my site shows broken

Please help me to resolve this soon as possible

**Comment by magefan** [comment]
@Krupaly2k could you please indicate what exactly folder was created? Please provide absolute folder path.

**Comment by Krupaly2k** [comment]
Its resolved now. It was just re-indexing issue. Thanks for quick help
