### ISSUE TITLE
Missing base table

### ISSUE THREAD

**Issue by deadlyw1re** [magefan/module-blog#116]
php bin/magento setup:upgrade

Base table or view not found: 1146 Table 'magefan_blog_post' doesn't exist, query was: DESCRIBE `magefan_blog_post`

**Comment by magefan** [comment]
Try to remove all magefan_blog tables from your database and remove the information about magefan blog extension from table setup_module and then re-run installation commands.

Please try take a look into step 3 https://github.com/magefan/module-blog/wiki/How-to-remove-Magefan-Blog-extension
