### ISSUE TITLE
Blog Index just showing "blog"

### ISSUE THREAD

**Issue by pmjcreations** [magefan/module-blog#119]
When I access to `/blog` it is just showing a string _blog_, in fact, a dummy page inserted by custom theme called [Novetty](https://themeforest.net/item/novetty-fastest-most-customizable-magento-2-theme/18197526). If I change content on this page, it is getting updated.

I have compared your demo admin section with my admin configuration and found nothing different.
If I disable this blog page, then it throws 404.

I tried a test on a clean installation, the same result there as well.

Blog Extension v2.6.2
Magento ver. 2.2.2

**Comment by magefan** [comment]
please make sure that you don't use any other blog extension or extension with route name "blog"

**Comment by pmjcreations** [comment]
Nope, I have only installed Magefan blog extension. As I said, this is happening in a clean installation as well.

**Comment by magefan** [comment]
What version of magento do you use for clean installation?

**Comment by pmjcreations** [comment]
Magento ver. 2.2.2 using Softaculous

**Comment by magefan** [comment]
We have re-tested blog extension on fresh magento 2.2.2 installation and cannot reproduce this issue

**Comment by pmjcreations** [comment]
Could you tell me if there is any configuration that I need to check which may cause such errors in server side?
I have installed this custom theme which carries Magefan blog extension a few months ago, and everything was working fine then. Now, I don't know if something went wrong during any of the update processes.
As I said, this is happening with even a fresh installation. Published blogs got listed well in `/blog` using Magento's default Luma theme before installing my custom theme/Magefan extension. After installing them, only this is happening.
And both test domain and production domain is interestingly on the same machine set up.

**Comment by magefan** [comment]
If you can provide ssh and admin panel credentials, please contact us via email support@magefan.com and we will check the issue other wise we don't have ability to help you :-(

**Comment by magefan** [comment]
The problem was in CMS page with url key = blog. Just removed this page.

**Comment by pmjcreations** [comment]
Ah, interestingly, I have disabled this CMS page and checked it. I never thought, disabling is different than deleting.

Thanks a ton @magefan
