### ISSUE TITLE
Category issue

### ISSUE THREAD

**Issue by parthiban-1992** [magefan/module-blog#12]
Hi,

Can u pls tell me how to move the categories from breadcrumbs area to top menu category area in this block.

Thanks,

**Comment by IhorVansach** [comment]
Do you mean to put blog categories to catalog categories menu?

**Comment by parthiban-1992** [comment]
I need to create a category in blog and assign the post to the category
like WordPress

**Comment by IhorVansach** [comment]
You can create new Blog category by
Admin Panel > Content (Left Menu Time) > Blog > Categories > Add New Category
To add new post, please follow:
Admin Panel > Content (Left Menu Time) > Blog > Posts > Add New Post
and set "Categories" in "Post Information" Tab

Or this is not you are looking for?
