### ISSUE TITLE
Unable to edit blog post

### ISSUE THREAD

**Issue by nikolaybaychenko** [magefan/module-blog#123]
I am unable to edit blog posts in versions above 2.6.1. The error occurs on edit blog post page load. Here is the error I receive in a report:
```
a:4:{i:0;s:97:"The requested component ("settings") is not found. Before using, you must add the implementation.";i:1;s:8639:"#0 /data/sites/<website_name>/releases/20180111094625/vendor/magento/module-ui/Model/Manager.php(207): Magento\Framework\View\Element\UiComponent\$
```

**Comment by magefan** [comment]
I think you are using Magento 2.1.x if yes, please update blog extension to the newest version 2.7.0
