### ISSUE TITLE
how to change "blog" from url in magento2.1

### ISSUE THREAD

**Issue by sanganagouda1** [magefan/module-blog#125]
how to change the url from "http://magento2/blog/post/post-name/" to
so i want to change url like "http://magento2/news/new/post-name/ ??

**Comment by magefan** [comment]
Please navigate to Stores > Configuration > Blog > Permalink Settings to change this.

@sanganagouda1, do not duplicate your message on different issues.

**Comment by sanganagouda1** [comment]
hi 
ya sorry for that but in my module i dont have that settings

**Comment by magefan** [comment]
I think you are using some old version of blog extension. Please update it to the newer one.
