### ISSUE TITLE
How to change page layout 2colums-right at blog_default.xml to 1column

### ISSUE THREAD

**Issue by taimaiduc** [magefan/module-blog#126]
How to change page layout 2colums-right at blog_default.xml to 1column. I want to remove sidebar by 
```
<?xml version="1.0"?>
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" layout="1column" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
    <body>
        <referenceBlock name="blog.sidebar" remove="true" />
    </body>
</page>

```

**Comment by magefan** [comment]
@taimaiduc , try to copy blog_default.xml  to your theme and then change 2columns-right to 1column

**Comment by taimaiduc** [comment]
It working. I put it on app\code\Vendor\Module
Can you explain why at app\code\Vendor\Module it not working?

**Comment by magefan** [comment]
Sorry, this issues section only for issues in blog extensions.

**Comment by taimaiduc** [comment]
@magefan thank you
