### ISSUE TITLE
[Request] I hope you can add feature related product at category form backend.

### ISSUE THREAD

**Issue by taimaiduc** [magefan/module-blog#127]
I hope you can update a field related product at category

![screenshot-blog demo magefan com-2018-01-24-22-43-46-134](https://user-images.githubusercontent.com/10907980/35341416-39f22944-0158-11e8-9068-7746e2a2780f.png)

**Comment by magefan** [comment]
Thank you for your suggestion. This feature is added to our backlog. But I cannot tell you when exactly  It will be done. If you need it right now you can contact us https://magefan.com/contact and we will provide a quote.
