### ISSUE TITLE
Can not override blog_post_form.xml

### ISSUE THREAD

**Issue by taimaiduc** [magefan/module-blog#129]
I have been override module-blog/view/adminhtml/ui_component/blog_post_form.xml in my custom module. I try to change some label or remove some field but not working. Can you give me a sunshine?

**Comment by magefan** [comment]
@taimaiduc We're not sure if you can remove any elements, but to change labels please try to use a sequence with Magefan_Blog in your module.xml (e.g.: https://github.com/magefan/module-blog/blob/master/etc/module.xml use sequence with Magento_Cms, Magento_Catalog) or use translations to change the label text.

**Comment by taimaiduc** [comment]
I found the reason why is Magento override by a->z. My vendor has to after M(egafan) character.
Thanks for sharing good extension
