### ISSUE TITLE
_addBreadcrumbs error on Posts page

### ISSUE THREAD

**Issue by chris-brabender** [magefan/module-blog#13]
After a fresh installation of the blog module, I added a new category to get it all to display.

The home page for the blog loads fine, and so does the category page. The hello world post displays in on both pages but clicking in to view the post results in this error:

    Recoverable Error: Argument 1 passed to Magefan\Blog\Block\Post\View::_addBreadcrumbs() must be an instance of Magefan\Blog\Model\Post, null given, called in vendor/magefan/module-blog/Block/Post/View.php on line 25 and defined in vendor/magefan/module-blog/Block/Post/View.php on line 41

Changing:

    $post = $this->getPost();

To: 

    $post = $this->_post;

Temporarily fixes the problem for me but it appears the execute() function in the Controller\Post\View action is not being triggered.

**Comment by chris-brabender** [comment]
It's weird, this happens on our local environment but not on our development servers. I'll keep looking into this myself and see what I can find.

**Comment by IhorVansach** [comment]
please check if you have the latest version of https://github.com/IhorVansach/Blog-Extension-for-Magento-2/blob/master/Block/Post/View.php

**Comment by chris-brabender** [comment]
yep these files are identical

**Comment by IhorVansach** [comment]
Chris, could you please contact to our support via email: support@magefan.com
We cannot reproduce this issue on our side.

**Comment by Sanuch** [comment]
It happens when we use varnish. Magento prepares esi call [ProcessLayoutRenderElement.php#L55-L62](https://github.com/magento/magento2/blob/develop/app/code/Magento/PageCache/Observer/ProcessLayoutRenderElement.php#L55-L62) for varnish.
When we receive request `/page_cache/block/esi/blocks/[%22catalog.topnav%22]/handles/[%22default%22,%22blog_post_view%22]/` then your module does not know about current post

**Comment by magefan** [comment]
Sanuch, please try the last fix

**Comment by Sanuch** [comment]
Hi @magefan,
It works

**Comment by chris-brabender** [comment]
@magefan thanks for these updates, could you possible add a new tag so we can pull these down?

**Comment by magefan** [comment]
@chris-brabender the tag will be available soon
