### ISSUE TITLE
Fatal error: Call to a member function setPost() on boolean in \app\code\Magefan\Stories\Block\Post\PostList.php on line 29

### ISSUE THREAD

**Issue by goudas** [magefan/module-blog#130]
Hi,
we are using old module because we have so many changes and we trying to change url blog to stories so when we changed then getting above error so please do the needful.
in Fatal error: Call to a member function setPost() on boolean in C:\xampp\htdocs\site1_dev\app\code\Magefan\Stories\Block\Post\PostList.php on line 29
`   public function getPostHtml($post)
    {
    	return $this->getChildBlock('stories.posts.list.item')->setPost($post)->toHtml();
    }
`

**Comment by Ksardarion** [comment]
You catch this error `cause your $post == false
(I`m not sure, but It`s have a reason to think about what your $post equal)

**Comment by magefan** [comment]
Hello @goudas, please note, that this Issue section is only for issues in official Magefan Blog releases.
You get this issue as there is no child block 'stories.posts.list.item' in your block. Try to make something like this 

```
public function getPostHtml($post) {
	$itemBlock = $this->getChildBlock('stories.posts.list.item');
	if ($itemBlock) {
		return $itemBlock->setPost($post)->toHtml();
	}

	return false;
}
```

or check your layout structure.

**Comment by muhalik** [comment]
basically there are two concept one is static member function and one is non static member function i recommend you check out this blog https://www.info999.gq/2020/08/member-functions-in-c.html
