### ISSUE TITLE
Installing new version of Magefan Blog

### ISSUE THREAD

**Issue by jsoftwares** [magefan/module-blog#131]
Hi we try to copy new version of blog code and ran this command:
php bin/magento setup:upgrade
On completion the below error us shown on command line. Also magento site stops opening even after running:  php bin/magento setup:di:compile
php bin/magento setup:static-content:deploy

Please how can this be resolved?

[Exception]
  Warning: PDOStatement::execute(): MySQL server has gone away in /magento_root/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php on li
  ne 228

**Comment by jsoftwares** [comment]
Note: after I revert to old version of Magefan extension, downloaded in 2016. Everything works normal.

**Comment by magefan** [comment]
Hello @jsoftwares we don't think that this is related to our blog extension. This is common Magento 2 issue when the webserver isn't configurated properly.  Please take a look at this articles to find the solution:
http://devdocs.magento.com/guides/v2.2/install-gde/trouble/tshoot_mysql_table-open-cache.html
https://www.google.com/search?q=magento+2+setup+upgrade+mysql+server+has+gone+away

**Comment by jsoftwares** [comment]
Thank you very much @magefan 
I will read through and correct error or look for some with more experience to help if cannot
