### ISSUE TITLE
Fail to upload featured image for blog post on Safari browser

### ISSUE THREAD

**Issue by nikolaybaychenko** [magefan/module-blog#139]
I am unable to upload featured image (Posts -> Add New Post -> Additional Options -> Featured Image) for a blog post on Safari browser. When I choose an image to upload the uploading process loops and image does't upload.

**Comment by magefan** [comment]
Can you please try to upload image for the default magento catalog category to look if it works

**Comment by nikolaybaychenko** [comment]
@magefan This is an interesting observation, you were right to point out there. I tried to upload an image to catalog category, the problem was the same as with uploading an image for a post featured image. I then found an [issue](https://github.com/magento/magento2/issues/10804) on Magento 2 GitHub repository where it was pointed out that this problem was fixed in 2.2 version. I tested it on 2.2 and it turned out to be true.
