### ISSUE TITLE
Upgrade from 2.5.1 fails

### ISSUE THREAD

**Issue by Bobstar040** [magefan/module-blog#140]
i use m2.2.3 i deleted manual installation of 2.5.1 and installed a the new version via composer require magefan/module-blog-m22

I now get this error in console after php bin/magento setup:upgrade

Warning: PDOStatement::execute(): MySQL server has gone away in /home/bobstores/domains/bobstores.nl/public_html/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php on line 228

**m2 frontend**

1 exception(s):
Exception #0 (Magento\Framework\Exception\LocalizedException): Please upgrade your database: Run "bin/magento setup:upgrade" from the Magento root directory.
The following modules are outdated:
Magefan_Blog schema: current version - 2.5.1, required version - 2.7.1
Magefan_Blog data: current version - 2.5.1, required version - 2.7.1
Magefan_BlogM22 schema: current version - none, required version - 2.0.0
Magefan_BlogM22 data: current version - none, required version - 2.0.0

Exception #0 (Magento\Framework\Exception\LocalizedException): Please upgrade your database: Run "bin/magento setup:upgrade" from the Magento root directory.
The following modules are outdated:
Magefan_Blog schema: current version - 2.5.1, required version - 2.7.1
Magefan_Blog data: current version - 2.5.1, required version - 2.7.1
Magefan_BlogM22 schema: current version - none, required version - 2.0.0
Magefan_BlogM22 data: current version - none, required version - 2.0.0
#0 /home/bobstores/domains/bobstores.nl/public_html/vendor/magento/framework/Interception/Interceptor.php(121): Magento\Framework\Module\Plugin\DbStatusValidator->beforeDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Magento\Framework\App\Request\Http))
#1 /home/bobstores/domains/bobstores.nl/public_html/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(73): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#2 /home/bobstores/domains/bobstores.nl/public_html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#3 /home/bobstores/domains/bobstores.nl/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#4 /home/bobstores/domains/bobstores.nl/public_html/generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#5 /home/bobstores/domains/bobstores.nl/public_html/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#6 /home/bobstores/domains/bobstores.nl/public_html/generated/code/Magento/Framework/App/Http/Interceptor.php(24): Magento\Framework\App\Http->launch()
#7 /home/bobstores/domains/bobstores.nl/public_html/vendor/magento/framework/App/Bootstrap.php(256): Magento\Framework\App\Http\Interceptor->launch()
#8 /home/bobstores/domains/bobstores.nl/public_html/index.php(108): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#9 {main}

Any idea how to solve this?

**Comment by magefan** [comment]
"MySQL server has gone away" is not related to our blog extension but to the magento 2 itself. Please try to google the solution.

**Comment by Bobstar040** [comment]
Yes i already found another user on your github who had the same issue, we
are working on that. Thanks for the quick reply!



2018-03-05 13:35 GMT+01:00 Magefan <notifications@github.com>:
