### ISSUE TITLE
Magento 2.2.3 - Setup Upgrade faild with Mysql Server Has Gone Away when Updating Module

### ISSUE THREAD

**Issue by harrigo** [magefan/module-blog#142]
I have updated the version of the plugin to version 2.7.1 from 2.4.4. 

Setup upgrade stop each time at "Module Magefan_Blog" with below error:
Upgrading schema.. Warning: PDOStatement::execute(): MySQL server has gone away in /home/sites/magento/testing_html/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php on line 228

I have recently updated Magento from 2.2.1 to 2.2.3 and this seems to go ok. On updating this module however the magefan_blog_posts table seems to become corrupt and cannot be seen within mysql. I cannot restore it as it seems to think it exists so have to restore backup. 

Mysql throws errors like below:
```
2018-03-12 10:53:10 0x7f3d1d8bc700  InnoDB: Assertion failure in thread 139900465432320 in file pars0pars.cc line 822
InnoDB: Failing assertion: sym_node->table != NULL
InnoDB: We intentionally generate a memory trap.
InnoDB: Submit a detailed bug report to http://bugs.mysql.com.
InnoDB: If you get repeated assertion failures or crashes, even
InnoDB: immediately after the mysqld startup, there may be
InnoDB: corruption in the InnoDB tablespace. Please refer to
InnoDB: http://dev.mysql.com/doc/refman/5.7/en/forcing-innodb-recovery.html
InnoDB: about forcing recovery.
10:53:10 UTC - mysqld got signal 6 ;
This could be because you hit a bug. It is also possible that this binary
or one of the libraries it was linked against is corrupt, improperly built,
or misconfigured. This error can also be caused by malfunctioning hardware.
Attempting to collect some information that could help diagnose the problem.
As this is a crash and something is definitely wrong, the information
collection process might fail.
Please help us make Percona Server better by reporting any
bugs at http://bugs.percona.com/
```

**Comment by davidwindell** [comment]
@harrigo did you manage to resolve this?

**Comment by harrigo** [comment]
I think there is a way if you do it in a certain order as my dev site
works.

Not sure if I updated without the setup scripts. Dropped the version back
in database and then updated again. Don't quote me on that however and make
many a backup I completely broke my database table for posts at one point
after multiple attempts at setup upgrade.

I need to figure out the process however soon as need to update the module
on live site still.

Is this an issue for you also?

**Comment by davidwindell** [comment]
Thanks, we're having the exact same allocation failure (not with a Mage Fan module) but it only started after upgrading to MySQL (AWS Aurora) 5.7.

**Comment by alinalexandru** [comment]
I am having the same problem, but it is not related with this module. It seems that there is a problem in mysql https://bugs.mysql.com/bug.php?id=68987
I am having the problem on a magento module when I run the upgrade.

**Comment by magefan** [comment]
In case anyone still have this issue, you can try to remove some deprecated blog post FULLTEXT indexes before update the extension. For this run SQL query:

> ALTER TABLE magefan_blog_post DROP INDEX MAGEFAN_BLOG_POST_TITLE;
> ALTER TABLE magefan_blog_post DROP INDEX MAGEFAN_BLOG_POST_CONTENT;
> ALTER TABLE magefan_blog_post DROP INDEX MAGEFAN_BLOG_POST_SHORT_CONTENT;
