### ISSUE TITLE
Wrong URL Creation

### ISSUE THREAD

**Issue by afavata** [magefan/module-blog#149]
Magento 2.2.3
Magefan Module Blog 2.7.1

Creating a new blog post URL string is populate with wrong text.

Current Status - Example
Post Title: This is a test 
URL created: this is a test

instead of:

URL: this-is-a-test

This generate an error when try to access to the post from the frontend

Thanks 

Alessandro

**Comment by magefan** [comment]
Hello @afavata , thank you, this is a known issue, here is a fix
https://github.com/magefan/module-blog/commit/527d0c07d42e9d3c05bd662fe9cacd7f4720b696

It will be included in next v2.8.0, that will be released on Monday (28/03/2018)
