### ISSUE TITLE
Backlinks

### ISSUE THREAD

**Issue by devdesco-ceo** [magefan/module-blog#15]
Игорь, стыдно предлагать бесплатное расширение, и вкраплять обратные ссылки на свой сайт!

Я так понимаю, что если делать что-то "совершенно" бесплатным, так оно и должно быть беплатным, без всяких выкидонов!!!

![image 2016-03-21 20 24 19](https://cloud.githubusercontent.com/assets/8983883/13939613/799af386-efa4-11e5-9abf-17731b47c4a6.png)

**Comment by IhorVansach** [comment]
Backlinks is common practice for free extensions. You can often see them in the WordPress plugins or themes and you always can easy remove them.

Since there is dissatisfaction from your side - I have removed them from magento 2 blog extension by last commit.

Viktor, please let me know if you have any other concerns.

**Comment by devdesco-ceo** [comment]
Ihor, if you want some $$$ for your extension, and at the same time keep the word out, I suggest you make a link in the settings page for your blog, where you can ask for a donation. Depending on the feature set of your extension, it might beat other paid blog extensions, and you can collect lots of $$$ for just asking for a donation, but not inserting backlinks to your site in stealth.

Please understand, whoever sets up a web store based on magento, he is not doing that for fun like setting up a WP blog. These are completely different worlds, so in my humble opinion, backlinks in a store front are a NO NO in any scenario.

**Comment by IhorVansach** [comment]
Viktor, thank you for your advice.
Did last commit (b35bbd37be71328a54a77afbb55c82dd6ef38c48) remove backlinks (is it working for you)?

**Comment by devdesco-ceo** [comment]
Did not check yet.

Can you make a widget that can be used across M2 website to bring up latest/Hot posts in different display formats?

**Comment by magefan** [comment]
yes. pls create separate issue for this.
