### ISSUE TITLE
Translation to Hebrew

### ISSUE THREAD

**Issue by eladnm** [magefan/module-blog#152]
Hi,

Thanks for this great module. I am preparing an Hebrew translation by creating he_HE.csv file and i wanted to know how to apply the translation to the blog. 

i need to put it in the i18n folder and than?

**Comment by magefan** [comment]
Hello @eladnm you need to place it into i18n in the blog folder https://github.com/magefan/module-blog/tree/master/i18n and then flush magento cache.

Could you please send us he_HE.csv file via email support@magefan.com and we will add it to the module repository, so it can be included in the next release automatically?

**Comment by eladnm** [comment]
Sure, I will email you the file when I am done. how will magento will know to take the he_HE.csv file and apply it to the blog? i dont need to config anything and direct to the he_HE.csv file?

**Comment by eladnm** [comment]
so i have to run?
php bin/magento setup:di:compile
php bin/magento setup:static-content:deploy

**Comment by magefan** [comment]
no,
1. Make sure that in Stores > Configuration  he_HE has been set as locale
2. add file to app/code/Magefan/Blog/i18n/he_HE.csv or vendor/magefan/module-blog/i18n/he_HE.csv
3. run php bin/magento cache:clean

**Comment by eladnm** [comment]
Doesn't seem to work. For example I translated the word recent post but it's still in English.
https://www.deals4u.co.il/blog

**Comment by magefan** [comment]
Could you please send the .csv file to us, and we will check.
As the suggestion, the issue can be in the theme templates.

**Comment by eladnm** [comment]
issue fixed, the file should be he_IL.csv. 
I will email it to you when i am done translating all the words.

**Comment by magefan** [comment]
@eladnm , is everything OK or you have some issues with he_IL? Could we ask you please to share the he_IL.csv file so we can include it in the next release?

**Comment by eladnm** [comment]
Hi @magefan, I will email it to you later today. I completed the translation of the important words but not all words.
