### ISSUE TITLE
Error when editing or creating posts

### ISSUE THREAD

**Issue by stevenlavine** [magefan/module-blog#154]
Hi,

Since updating the blog extension to 2.8.0 I am getting the following error message when attempting to edit or create new posts.

Something went wrong while saving this post. Element 'htmlContent': This element is not expected. Expected is one of ( field, fieldset, container, dataSource, insertForm, insertListing, modal ). Line: 9

I updated the extension from version 2.5.1

Your assistance in this matter would be appreciated.

Regards,

Steve

**Comment by magefan** [comment]
Hello @stevenlavine ,

We think you use Magento 2.1.x if yes, please make sure that this extension is not installed on your magento (https://github.com/magefan/module-blog-m22)

**Comment by stevenlavine** [comment]
Yes, My mistake. I inadvertently installed the M22 extension on an 2.1.x installation (facepalm)

**Comment by magefan** [comment]
So, all you need to do is to remove magefan/module-blog-m22, it is only for Magento 2.2.x
