### ISSUE TITLE
Can't upadte blog post when editing in french (date format dd/mm/YYYY)

### ISSUE THREAD

**Issue by kennedyabitbol** [magefan/module-blog#155]
Magento 2.1.12, Magefan Blog 2.8.0

In french admin.
When i create a blog content without fill any date, i works fine, when i edit an existing post, i got whatever date i choose, an error displayed:

> Un problème est survenu lors de l'enregistrement post. Invalid input date format '26/03/2018'

This problem does not appears in english.

**Comment by magefan** [comment]
This issue duplicate https://github.com/magefan/module-blog/issues/30
