### ISSUE TITLE
Fatal Error when updating to 2.8.0

### ISSUE THREAD

**Issue by pioneerathletics** [magefan/module-blog#157]
Trying to upgrade from 2.7.1 to 2.8.0 but encountering a fatal error when re-compiling

Magento 2.1.12
Production Mode
All caches enabled

php bin/magento setup:upgrade
php bin/magento setup:di:compile

**After running compile fatal error is show:**
`Compilation was started.
Proxies code generation... 0/7 [>---------------------------]   0% 1 sec 44.0 MiProxies code generation... 1/7 [====>-----------------------]  14% 1 sec 46.0 MiRepositories code generation... 1/7 [====>-----------------------]  14% 1 sec 46.0 MiBPHP Fatal error:  Class 'Magefan\Community\Controller\Adminhtml\Actions' not found in /xxxx/xxxxx/xxxxx/app/code/Magefan/Blog/Controller/Adminhtml/Actions.php on line 14`

**Comment by magefan** [comment]
You need to install https://github.com/magefan/module-community to fix this issue
