### ISSUE TITLE
Error during compilation mode

### ISSUE THREAD

**Issue by Vout** [magefan/module-blog#161]
After updating the module to the latest 2.8.0 version i'm experiencing some issues while setting the environment to production mode.

When doing `bin/magento setup:di:compile` i'm getting the following error back,

`Repositories code generation... 1/7 [====>-----------------------]  14% 1 sec 52.0 MiBPHP Fatal error:  Class 'Magefan\Community\Controller\Adminhtml\Actions' not found in /var/www/production/app/code/Magefan/Blog/Controller/Adminhtml/Actions.php on line 14`

I'm using the latest (2.2.4) version of Magento, clean install with no other extensions. Any suggestions?

**Comment by magefan** [comment]
Hello @Vout , this is duplicate of issue https://github.com/magefan/module-blog/issues/157
