### ISSUE TITLE
Missing class Magefan\Community\Controller\Adminhtml\Actions

### ISSUE THREAD

**Issue by Anantkprajapati** [magefan/module-blog#163]
Fatal error: Class 'Magefan\Community\Controller\Adminhtml\Actions' not found in app/code/Magefan/Blog/Controller/Adminhtml/Actions.php on line 1

**Comment by magefan** [comment]
This is duplicate for issue https://github.com/magefan/module-blog/issues/157

**Comment by Anantkprajapati** [comment]
This is happen when i download the module and add it under app/code 
But i removed from it and run the below commands and its looking like fixed
composer require magefan/module-blog
php bin/magento setup:upgrade
php bin/magento setup:di:compile
php bin/magento setup:static-content:deploy

but it should work if direct download it and put it under app/code without run composer command

Thank you

**Comment by Anantkprajapati** [comment]
okay thank you... 

Can you please set those full setup in github.. So, this should not happen or add noted in README

**Comment by magefan** [comment]
It is already there 
https://prnt.sc/jmhnmt

**Comment by nimbus2300** [comment]
Thanks - this worked for me...

To summarise: I wanted to run magefan/module-blog out of my app/code area (to make changes), but it failed with the error: 

`PHP Fatal error:  Class 'Magefan\Community\Controller\Adminhtml\Actions' not found`

It needed Magefan\Community, so to fix this message I had download and install magefan/module-community.

**Comment by magefan** [comment]
@nimbus2300 , try to install extensions via the composer, in such case, all dependencies will be installed automatically, or download the extensions from the vendor websites.
If you download the module from our store, then the community module will be included in the archive
https://magefan.com/magento2-blog-extension
