### ISSUE TITLE
Upgrade from 2.1 - 2.2 - Errors During Compilation

### ISSUE THREAD

**Issue by pioneerathletics** [magefan/module-blog#164]
Upgraded from Magento version - 2.1.12 to 2.2.4
Magefan Blog version - 2.8.0

Error when running setup:di:compile command:

`Errors during compilation:
	Mageplaza\Blog\Model\ResourceModel\Topic\Grid\Collection
		Incompatible argument type: Required type: \Magento\Framework\DB\Adapter\AdapterInterface. Actual type: \Mageplaza\Blog\Model\ResourceModel\Topic\Grid\connection; File: 
/xxxx/xxxx/xxxxxxx/app/code/Mageplaza/Blog/Model/ResourceModel/Topic/Grid/Collection.php

	Mageplaza\Blog\Model\ResourceModel\Tag\Grid\Collection
		Incompatible argument type: Required type: \Magento\Framework\DB\Adapter\AdapterInterface. Actual type: \Mageplaza\Blog\Model\ResourceModel\Tag\Grid\connection; File: 
/xxxxxx/xxxxxx/xxxxxx/app/code/Mageplaza/Blog/Model/ResourceModel/Tag/Grid/Collection.php

	Mageplaza\Blog\Model\ResourceModel\Post\Grid\Collection
		Incompatible argument type: Required type: \Magento\Framework\DB\Adapter\AdapterInterface. Actual type: \Mageplaza\Blog\Model\ResourceModel\Post\Grid\connection; File: 
/xxxxxx/xxxxxx/xxxxxx/app/code/Mageplaza/Blog/Model/ResourceModel/Post/Grid/Collection.php

Total Errors Count: 3

                                           
  [Magento\Framework\Validator\Exception]  
  Error during compilation                 
                                           `

Please advise.

**Comment by magefan** [comment]
@pioneerathletics  the issue is not related to Magefan Blog, if you'll check, you will see that error happens in Mageplaza\Blog\Model\ResourceModel\Topic\Grid\Collection.
Mageplaza is not Magefan.

If you don`t use Mageplaza Blog, you can disable it or remove.

**Comment by pioneerathletics** [comment]
Oh my goodness, my mistake.
