### ISSUE TITLE
Your contact email doesn't work & I translated your blog to french

### ISSUE THREAD

**Issue by Yonn-Trimoreau** [magefan/module-blog#17]
Hello,

When I try to send a mail to you, there's this message :
> SMTP error from remote mail server after RCPT TO:<support@magefan.com>:
> host mx1.mail6.freehost.com.ua [194.0.200.225]:
> 550 Relay not permitted

And by the way, here is what I wanted to send to you :
> Hi,
> 
> I translated your blog module from english to french ! If you want to reuse it or if someone asks for it : here it is ;)
> 
> By the way, thank you for the module, it's really helpful !
> 
> Have a nice day,

Here's the link : http://www.filedropper.com/frfr

**Comment by magefan** [comment]
Hello, thank you for report about mail problems on website (now it's fixed) and thank you for help with translation.
The link you provided is not currently available. Could you please provide a new link or send archive over email?
