### ISSUE TITLE
Use default Magento template for related products 

### ISSUE THREAD

**Issue by Stevie-Ray** [magefan/module-blog#177]
It would be nice if Magefan_Blog made use of the default `vendor/magento/module-catalog/view/frontend/templates/product/list/items.phtml` for the related products template instead of having it's own custom template in `vendor/magefan/module-blog/view/frontend/templates/post/view/relatedproducts.phtml`.

**Comment by magefan** [comment]
@Stevie-Ray , thank you for the suggestion, we will add this to our backlog

**Comment by ihorvansach** [comment]
@Stevie-Ray , just want you to know that we have done this 
https://github.com/magefan/module-blog/commit/ea4be2f38b42f023ebb33d5572eb52a9c2652741

This feature will be included in the next blog extension v2.9.3

**Comment by Stevie-Ray** [comment]
@ihor-klymchuk nice, thanks for the update i'll give it a try!

**Comment by ihorvansach** [comment]
@Stevie-Ray , autocomplete is evil :-) this is not the first time when someone hit @ihor-klymchuk instead of me  @ihorvansach :-)
