### ISSUE TITLE
For mutli store store views are not saving in blog post

### ISSUE THREAD

**Issue by pieal86** [magefan/module-blog#181]
with mulit store and different store view which are language not saving if select multiple.
before save:
![bfrbp](https://user-images.githubusercontent.com/17842620/44622655-84dbbf00-a8de-11e8-9918-de694e86e2c3.png)
After Save: 
![afterbp](https://user-images.githubusercontent.com/17842620/44622656-8e652700-a8de-11e8-8d51-8794cebe3009.png)

**Comment by magefan** [comment]
Hello @pieal86 , we have made a test on the latest Magento 2.2.5 with Magefan blog v2.8.2 and there is no such issue. Make sure that you use latest version for blog extension
