### ISSUE TITLE
Greek translation

### ISSUE THREAD

**Issue by dmarkos** [magefan/module-blog#182]
How could I approach translating the blog module? I installed via composer and I wouldn't want to touch the vendor folder. If solved, I could give it back as a contribution I guess.

**Comment by magefan** [comment]
@dmarkos , please temporary create el_GR.csv in vendor
use the command
cp vendor/magefan/i18n/en_US.csv vendor/magefan/i18n/el_GR.csv
make the translation, send it to as and we will include el_GR to the codebase asap

**Comment by dmarkos** [comment]
Yes, this is what I thought I should do. I will complete the translation
and send it to you.

**Comment by magefan** [comment]
@dmarkos , have you already done el_GR translation? If yes, could you please share it with us?

**Comment by dmarkos** [comment]
Is done. 

[el_GR.zip](https://github.com/magefan/module-blog/files/2378744/el_GR.zip)

**Comment by magefan** [comment]
Thank you. The file has been added 
https://github.com/magefan/module-blog/commit/69b64418927c0880f044b21555c00c5f922cbaea

and will be included in next release.
