### ISSUE TITLE
Position / sorting of categories

### ISSUE THREAD

**Issue by DePalmo** [magefan/module-blog#183]
Hello,

Some time ago I dropped you an email about sorting of categories and that it does not work correctly. You then responded that "Position" uses a DESC when sorting categories, but that does not feel natural, I would expect that position 1 is higher than position 5, but in your extension this is reversed, so position 5 will be higher than position 1. At that time I already proposed a solution to change the code in `Magefan\Blog\Block\Sidebar\Categories::getGroupedChilds` and update line 57 with `->setOrder('position', 'ASC')`, but now when I upgraded your extension to latest version, I see that this change was still not applied.

Since other extensions too use the "position" and it does work as I described it, would you consider to add the mentioned change into your next release?

Or am I (and others) understand "position" wrongly?

**Comment by DePalmo** [comment]
BTW, "position" that is set per post is being ignored, posts are always sorted by "created date" DESC.

**Comment by magefan** [comment]
This is fixed in the latest versions. Additionally [Magento Blog Extra ](https://magefan.com/magento2-blog-extension/pricing) has the option to define post position inside each category
