### ISSUE TITLE
REST API - get list of category, tags and comment

### ISSUE THREAD

**Issue by frankeymen** [magefan/module-blog#184]
Are there routes for getting category-, tag- and comments list like there is a route for getting a list of posts?

for posts it works:
`curl "http://mystore.com/index.php/rest/V1/blog/post/list/:type/:term/:store_id/:page/:limit`

for categories:?

`curl "http://mystore.com/index.php/rest/V1/blog/category/list/:type/:term/:store_id/:page/:limit`

**Comment by magefan** [comment]
Unfortunately for now, there is no option to get category list via the rest api

**Comment by magefan** [comment]
Now you can use [Magento 2 Blog GraphQL](https://github.com/magefan/module-blog-graph-ql) to get all data you need.
