### ISSUE TITLE
REST API - Get storeview data the default way

### ISSUE THREAD

**Issue by frankeymen** [magefan/module-blog#185]
The REST API routes requires the storeId in the route as following:

`http://mystore.com/index.php/rest/V1/blog/post/view/:id/:store_id`

Though Magento2 RESTAPI has uses the storecode to identify the store as following:

`http://mystore.com/index.php/:storecode/rest/V1`

**Comment by magefan** [comment]
@frankeymen ,  we have tested and the :storecode way

http://mystore.com/index.php/:storecode/rest/V1

only works when config option "Add Store Code to Urls" = YES

and some magento shops have this options disabled. So I think we cannot change this.
We will add to our back log a feature to use store_code in addition to store id.
