### ISSUE TITLE
Import Aw_Blog Magento 2

### ISSUE THREAD

**Issue by Stevie-Ray** [magefan/module-blog#186]
For a client we'd like to move from Aw_Blog to Magefan_Blog, is it possible to do a data migration? Because on your website it says: "aheadWorks blog for Magento 1." If not this would be a nice feature!

**Comment by magefan** [comment]
Hello @Stevie-Ray , yes our blog include a functionality of import blog from Aw_Blog (Magento 1).

**Comment by Stevie-Ray** [comment]
Would be nice to import posts from **Magento 2**, to switch modules.

**Comment by magefan** [comment]
@Stevie-Ray , you can extend this file 
https://github.com/magefan/module-blog/blob/master/Model/Import/Aw.php

to make it compatible with m2, or you can email us support@magefan.com and we will provide a quote for such modification.
