### ISSUE TITLE
Featured images overwritten

### ISSUE THREAD

**Issue by DePalmo** [magefan/module-blog#187]
Scenario:
- create a post with "featured image" named "001.jpg"
- create a second post with different "featured image" named "001.jpg"

First image will be overwritten.

**Comment by magefan** [comment]
Thank you for your report. We will check and fix the issue.

**Comment by magefan** [comment]
@DePalmo , this issue is fixed in [Magento 2 Blog Extension](https://magefan.com/magento2-extensions) v2.8.9

**Comment by DePalmo** [comment]
Thank you for letting me know!
