### ISSUE TITLE
[Feature request]: Sort / ordering per category

### ISSUE THREAD

**Issue by DePalmo** [magefan/module-blog#188]
Is it possible that we have a sorting of posts per category per desired field? For example one category would be sorted by position ASC and another by created date DESC.

**Comment by magefan** [comment]
Actually, it is already an option in the blog category settings " Posts Sort By", where you can choose:
Publish Date or Position https://prnt.sc/l7eucn

**Comment by DePalmo** [comment]
Thanks for the tip, will check it out.

**Comment by DePalmo** [comment]
You're correct, it's there but it has an issue. Please see #183
