### ISSUE TITLE
Category does show on storefront

### ISSUE THREAD

**Issue by Sanuch** [magefan/module-blog#19]
Hello

You allow to select "All Store Views" for post and when we assign this post to category which should shows only on one store then this category does not show on storefront.
It happens because you do not check if store_id for post is "0" and you filter category collection 
`AND (store_table.store_id IN('0', 0))`

**Comment by magefan** [comment]
@Sanuch, Fix is made. Try to update to the latest version.

**Comment by magefan** [comment]
@Sanuch, Is this issue fixed for you and can be closed?
