### ISSUE TITLE
Caching issue

### ISSUE THREAD

**Issue by DePalmo** [magefan/module-blog#190]
From time to time it happens that new posts are not visible until we clear Page Cache manually. Would appreciate if you can take a look into this.

Magento v2.2.3
Blog v2.8.2.1

**Comment by DePalmo** [comment]
Category list. It does not happen always, but frequent enough for us to notice. After we add new blog post, the category list does not reflect that change, but we have to manually clear FPC, then the new blog posts show.

**Comment by magefan** [comment]
This issue is fixed in the latest version of blog extension 2.9.2
