### ISSUE TITLE
[Feature request] ACL for rest API

### ISSUE THREAD

**Issue by taimaiduc** [magefan/module-blog#193]
Could you create ACL for rest API such as: create a blog, create a catalog

**Comment by taimaiduc** [comment]
https://github.com/magefan/module-blog/pull/194

**Comment by magefan** [comment]
Thx. Merged.

**Comment by magefan** [comment]
@t-perm , just want let you know that we changed acl rules added by you as they come with error. Here is code changes
https://github.com/magefan/module-blog/commit/77748a9bd7213742652b672941591b279dece424

**Comment by t-perm** [comment]
@magefan Thank you so much

**Comment by magefan** [comment]
@t-perm , in new blog v2.8.4 we have removed "create", "update" ACL and replace it with "save".

**Comment by t-perm** [comment]
@magefan thank you
