### ISSUE TITLE
Minify comment templates

### ISSUE THREAD

**Issue by Sanuch** [magefan/module-blog#20]
When minify is turn on then double slashes are removed as comment block

`s.src = '//<?php echo $block->getDisqusShortname() ?>.disqus.com/embed.js';`

This code will look as follows

`s.src = '.disqus.com/embed.js';`

**Comment by chris-brabender** [comment]
Some more info on this one, it happens in the view_preprocessed directory after running static content deploy and di compilation

It actually outputs:

    s.src = ' ?>.disqus.com/embed.js';

**Comment by magefan** [comment]
Have you entered your Disqus Shortname at blog configuration section (Admin Left Menu > Store > Configuration > Blog) ?

**Comment by Sanuch** [comment]
Yes, without minify it works

**Comment by magefan** [comment]
in file 
view/frontend/templates/post/view/comments.phtml
try to replace the code
```
s.src = '//<?php echo $block->getDisqusShortname() ?>.disqus.com/embed.js';
```
with the following
```
<?php $disqusJs = '//'.$block->getDisqusShortname().'.disqus.com/embed.js' ?>
s.src = '<?php echo $disqusJs ?>';
```

then clean cache and make redeploy.

Please let me know if this fix is working for you.

**Comment by magefan** [comment]
Updated my previews post.

**Comment by Sanuch** [comment]
OK, thanks
But you forgot about facebook because line
`js.src = "//connect.facebook.net/<?php echo $block->getLocaleCode() ?>/sdk.js#xfbml=1&version=v2.5&appId=<?php echo $block->getFacebookAppId() ?>";`
becomes
`js.src = " ?>";`

**Comment by magefan** [comment]
Thank you. it is fixed to.
