### ISSUE TITLE
Upgraded to 2.8.3 and cannot create new post

### ISSUE THREAD

**Issue by pioneerathletics** [magefan/module-blog#200]
Magento version: 2.1.15
Blog Version : 2.8.3

Hi, I just upgrade to the latest blog version and when I tried to create a new post I received this error message:

`Something went wrong while saving this post. The requested component ("settings") is not found. Before using, you must add the implementation.`

**Comment by magefan** [comment]
Hello @pioneerathletics,

In blog version 2.8.3 we have enabled media gallery by default for Magento 2.2.x (https://github.com/magefan/module-blog/commit/4ef8b5927fa663aafc42e7ba407a7f969421c0df) as a lot of M2.2.x customers complained about "missing gallery".
But `<settings>` node is not available in UI XML for Magento 2.1.x. so you need to edit 
`view/adminhtml/ui_component/blog_post_form.xml`
file in blog extension and remove or comment `<htmlContent>` node https://prnt.sc/l9as4k + flush magento cache.

**Note:** after your remove **htmlContent** the media gallery still will be available on M2.1.x
