### ISSUE TITLE
blog_sitemap.xml path

### ISSUE THREAD

**Issue by afavata** [magefan/module-blog#204]
Hello

I've recently installed the last version of the module on Magento 2.2.6.
Considering Magento strongly advises to point DocumentRoot on "pub" folder, there is no way for google search to catch the sitemap.xml file as per default it is stored in the main root folder.
Is there a way to save new blog sitemaps in other folders?
I did not find any option in the configuration settings.
Thanks

**Comment by magefan** [comment]
Hello @afavata , I think that this question is related to general magento configurations, not to the blog extension, as our module, use Magento logic to generate sitemaps.

I have a few suggestions for you:
1. You can make a symlink from sitemap.xml to pub/sitemap.xml
2. Change the sitemap settings and in the path field enter /pub/  https://prnt.sc/ldh5a4

**Comment by afavata** [comment]
Thank you for your reply… I understood that with blog latest release there's no blog_sitemap.xml generated with data related uniquely to blog. All have been included in the main magento sitemap.xml that easily can be stored in a chosen folder as per your screenshot.


Thank you
