### ISSUE TITLE
Searchbar issue (searching for posts)

### ISSUE THREAD

**Issue by leonhelmus** [magefan/module-blog#205]
Hello MageFan,

I've tried to install the blog module on magento 2.2 and it all works fine! Except for the search bar i get this error when searching for posts:
`Exception #0 (Zend_Db_Statement_Exception): SQLSTATE[HY000]: General error: 1191 Can't find FULLTEXT index matching the column list, query was: SELECT `main_table`.*, (0               + (MATCH (content) AGAINST ("hallo")) * 1               + (MATCH (content) AGAINST ("hallo")) * 2               + (MATCH (title) AGAINST ("hallo")) * 5) AS `search_rate` FROM `magefan_blog_post` AS `main_table`
 INNER JOIN `magefan_blog_post_store` AS `store_table` ON main_table.post_id = store_table.post_id WHERE (`is_active` = '1') AND (`publish_time` <= '2018-11-09 07:23:02') AND ((`title` LIKE '%hallo%') OR (`short_content` LIKE '%hallo%') OR (`content` LIKE '%hallo%')) AND (store_table.store_id IN('2', 0)) GROUP BY `main_table`.`post_id` ORDER BY search_rate DESC, publish_time DESC
 LIMIT 10
Exception #1 (PDOException): SQLSTATE[HY000]: General error: 1191 Can't find FULLTEXT index matching the column list`

Could you help me with this issue?

**Comment by magefan** [comment]
Hello @leonhelmus,

Thank you for the report. We have prepared a fix https://github.com/magefan/module-blog/commit/6748da7f3c78b88a125c56640920823672f00360
Please check.
Not that after you upload new files, you need to run the installation commands:
bin/magento setup:upgrade
bin/magento setup:di:compile
bin/magento setup:static-content:deploy

Let us know if it works for you.

**Comment by leonhelmus** [comment]
Ill test it now.

**Comment by leonhelmus** [comment]
It seems to working a lot better. Only problem now is that i get the error:
`Numeric value out of range: 1690 DOUBLE value is out of range in '((match `obelink_db_acc`.`main_table`.`title` against ('hello')) * 5)', query was: SELECT `main_table`.*, (0               + (MATCH (content) AGAINST ("hello")) * 1               + (MATCH (short_content) AGAINST ("hello")) * 2               + (MATCH (title) AGAINST ("hello")) * 5) AS `search_rate` FROM `magefan_blog_post` AS `main_table`
 INNER JOIN `magefan_blog_post_store` AS `store_table` ON main_table.post_id = store_table.post_id WHERE (`is_active` = '1') AND (`publish_time` <= '2018-11-09 12:27:44') AND ((`title` LIKE '%hello%') OR (`short_content` LIKE '%hello%') OR (`content` LIKE '%hello%')) AND (store_table.store_id IN('2', 0)) ORDER BY search_rate DESC, publish_time DESC
 LIMIT 10
Exception #1 (PDOException): SQLSTATE[22003]: Numeric value out of range: 1690 DOUBLE value is out of range in '((match `obelink_db_acc`.`main_table`.`title` against ('hello')) * 5)'
`
Could you help me with this last problem?

**Comment by leonhelmus** [comment]
It seems the only word i can't use is hello. It's really strange.

**Comment by leonhelmus** [comment]
and hello world. This is from your default data that is installed.

**Comment by leonhelmus** [comment]
It looks like when title and description have the same string inside of it.

**Comment by magefan** [comment]
@leonhelmus , please try to wait some time or make check, optimization, and repair of table
magefan_blog_post table in DB using phpMyAdmin.

**Comment by leonhelmus** [comment]
@magefan I have the time to wait no worries. Hope you can reproduce it. Would be really nice.

**Comment by leonhelmus** [comment]
@magefan Have you got some time to see why this happens?

**Comment by magefan** [comment]
@leonhelmus , we have released v2.8.5 that includes a fix for this issue, please update the extension.

**Comment by leonhelmus** [comment]
It's working now @magefan  Thx A LOT!!!

**Comment by BrentRobert** [comment]
@magefan In tagged version 2.8.5 this fix is not included?

https://github.com/magefan/module-blog/blob/2.8.5/Model/ResourceModel/Post/Collection.php

**Comment by magefan** [comment]
This fix was not quite good, so it was removed and other one have been added. If you use blog v2.8.5 and still have the search issue, please try to use this fix
https://github.com/magefan/module-blog/commit/ad60f5f35b3b0034acd6bde45d408cc605153e17
