### ISSUE TITLE
Issue updating from 2.8.3 to 2.8.4

### ISSUE THREAD

**Issue by afavata** [magefan/module-blog#206]
I updated to 2.8.4. 

frontend shows:
```
1 exception(s):
Exception #0 (Magento\Framework\Exception\LocalizedException): Please upgrade your database: Run "bin/magento setup:upgrade" from the Magento root directory.
The following modules are outdated:
Magefan_Community data: current version - 2.0.2, required version - 2.0.3
Magefan_Blog schema: current version - 2.8.3, required version - 2.8.4
Magefan_Blog data: current version - 2.8.3, required version - 2.8.4
```

During bin/magento setup: upgrade system shows
```
Module 'Magefan_Community':
Module 'Magefan_Blog':
Upgrading schema.. SQLSTATE[HY000]: General error: 1795 InnoDB presently supports one FULLTEXT index creation at a time
```

thank you

**Comment by magefan** [comment]
Hello @afavata ,

1. Do you use only Magefan_Blog or Magefa_BlogPlus too?
2. Have you previously manually added any FULLTEXT index to the title and content field in magefan_blog_post table?

**Comment by afavata** [comment]
Hello

I’m using “Magefan_blog”  and “login as customer”
No… never added any Fulltext index… I would not know how to do either

Thanks

Inviato da Posta<https://go.microsoft.com/fwlink/?LinkId=550986> per Windows 10

________________________________
Da: Magefan <notifications@github.com>
Inviato: Monday, November 12, 2018 6:38:26 AM
A: magefan/module-blog
Cc: Alessandro; Mention
Oggetto: Re: [magefan/module-blog] Issue updating from 2.8.3 to 2.8.4 (#206)


Hello @afavata<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fafavata&data=02%7C01%7C%7C9e6eb4ce4cba491ddd1608d648611248%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636775979080587332&sdata=sJNuzQpKtJ3UCQSyJjRsnOmAiEYbR5RuxjNUdznczNs%3D&reserved=0> ,

  1.  Do you use only Magefan_Blog or Magefa_BlogPlus too?
  2.  Have you previously manually added any FULLTEXT index to the title and content field in magefan_blog_post table?

**Comment by magefan** [comment]
Could you please send the details of your database server?

**Comment by magefan** [comment]
@afavata ,

Just a hotfix, you can remove this parts of code in next files
1. https://github.com/magefan/module-blog/blob/2.8.4.1/Model/ResourceModel/Post/Collection.php
https://prnt.sc/liev6q

2. https://github.com/magefan/module-blog/blob/2.8.4.1/Setup/UpgradeSchema.php
https://prnt.sc/lievp5

additional changes required if use Blog Plus or Blog Extra editions.

We already working on a solution and will try to include it in v2.8.4.2 as soon as it possible.

**Comment by magefan** [comment]
@afavata , we have released v2.8.5 that includes a fix for this issue, please update the extension.

**Comment by afavata** [comment]
Thanks

I'll try and let you know

Alessandro Favara
(+39) 338-9932106

________________________________

**Comment by afavata** [comment]
OK…. just upgraded. No issue reported during setup:upgrade.
All is working perfectly.

Thanks for your support!
