### ISSUE TITLE
Upgraded to 2.8.5 and cannot create new post

### ISSUE THREAD

**Issue by pioneerathletics** [magefan/module-blog#210]
Hi,
I recently updated to 2.8.5 and cannot create a new post.

Magento version- 2.1.14
Magefan blog version- 2.8.5

When I try to create anew post I get this error message - Something went wrong while saving this post. Notice: Undefined property: Magefan\Blog\Block\Adminhtml\Post\DeleteButton::$authorization in /xxxxx/xxxxx/dev2/app/code/Magefan/Blog/Block/Adminhtml/Post/DeleteButton.php on line 21.

**Comment by magefan** [comment]
@pioneerathletics , please make sure that you use the latest Magefan_Commnunity extension v2.0.3
https://github.com/magefan/module-community

**Comment by pioneerathletics** [comment]
@magefan, you are absolutely correct-everything works perfectly now thank you!
