### ISSUE TITLE
Exception: The element 'gallery' already has a child with alias 'content'

### ISSUE THREAD

**Issue by nocturnalfrog** [magefan/module-blog#211]
When you edit a blog post (in Magento 2.2.6) the following error is written to the exception.log.
> main.CRITICAL: The element 'gallery' already has a child with alias 'content' {"exception":"[object] (Magento\\Framework\\Exception\\LocalizedException(code: 0): The element 'gallery' already has a child with alias 'content' at /data/web/magento2/magento/vendor/magento/framework/Data/Structure.php:611)"} []

**Comment by magefan** [comment]
@nocturnalfrog, one gallery node is used for the Magento 2.1.x  and other one is for Magento 2.2.x, we will take a look what we can do with this.

**Comment by magefan** [comment]
@nocturnalfrog , this issue has been fixed in new release v2.8.6. Please confirm.

**Comment by nocturnalfrog** [comment]
Confirmed
