### ISSUE TITLE
Cant create category + duplicate save buttons

### ISSUE THREAD

**Issue by blopa** [magefan/module-blog#213]
Hello.

I am unable to create new categories, and when I try to create a new one, this happens:

https://i.imgur.com/xDTKwfe.png

Using: Magento 2.2.7 and Blog 2.8.5

Thank you

**Comment by magefan** [comment]
Hello @blopa , I think another blog extension is installed together with Magefan's one. You can check the list of all extensions in app/etc/config.php

Please disable all other blog extensions.

Let us know if this help.
