### ISSUE TITLE
Author Page

### ISSUE THREAD

**Issue by FadiNouh1** [magefan/module-blog#214]
Is there possibility to have an additional info on the Author page?
I need to add Information about every Author (maybe in adminitration of users page)  and then list the posts which are created by this author
thx

**Comment by magefan** [comment]
Hello @FadiNouh1 , right now we are finishing development of this feature for [Magento 2 Blog Extra extension](https://magefan.com/magento2-blog-extension). I think it will be available in the second part of next month.

**Comment by magefan** [comment]
@FadiNouh1 , Please use this fix to make blog extension works on M2.1.x properly
https://github.com/magefan/module-blog/issues/200

**Comment by FadiNouh1** [comment]
Thank you , it fixes it and I have now the latest version of your great extension :)
Is there a possible way to have expiration date of the post? like we set a date where the post will disappear from the blog?
Thanks for answering 👍

**Comment by magefan** [comment]
@FadiNouh1 , no, this is not possible now, we have added this to our backlog. Maybe it will be available in the next releases.

Fadi, could I ask you to leave a review about the extension at our website?
https://magefan.com/magento2-blog-extension

Best regards,
Magefan team

**Comment by FadiNouh1** [comment]
Thank you so much , sure 
going to add it :)
