### ISSUE TITLE
How to show blog.sidebar.recent on all pages in sidebar?

### ISSUE THREAD

**Issue by tukker01** [magefan/module-blog#217]
https://magefan.com/blog/recent-blog-posts-on-magento-2-homepage-sidebar/

**Comment by magefan** [comment]
@tukker01, this github section is only for bug reports.
Using the Magneto layout handle default.xml in your theme you can insert the block with class \Magefan\Blog\Block\Widget\Recent to your sidebar.
Please check Magento documentation to learn how to extend Magento layout.
