### ISSUE TITLE
Element 'block', attribute 'class': [facet 'pattern'] The value '\Magento\Framework\View\Element\Text\ListText' is not accepted by the pattern '[A-Z][a-zA-Z\d]*(\\[A-Z][a-zA-Z\d]*)*'.

### ISSUE THREAD

**Issue by cmucovic** [magefan/module-blog#220]
**STR:**
Go to http://bugfix-digi-59-exyu-characters-are-not-visible-on.digi.b.mementia.com/blog
Try to open blog article

**Actual result:**
There is an exception error:
Exception #0 (Magento\Framework\Config\Dom\ValidationException): Element 'block', attribute 'class': [facet 'pattern'] The value '\Magento\Framework\View\Element\Text\ListText' is not accepted by the pattern '[A-Z][a-zA-Z\d]*(\\[A-Z][a-zA-Z\d]*)*'.
Line: 929

Element 'block', attribute 'class': '\Magento\Framework\View\Element\Text\ListText' is not a valid value of the atomic type 'blockClassType'.
Line: 929

#0 /var/www/digi/b/bugfix-digi-59-exyu-characters-are-not-visible-on/public/vendor/magento/framework/Config/Dom.php(115): Magento\Framework\Config\Dom->_initDom('<layout xmlns:x...')
#1 /var/www/digi/b/bugfix-digi-59-exyu-characters-are-not-visible-on/public/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(111): Magento\Framework\Config\Dom->__construct('<layout xmlns:x...', Object(Magento\Framework\App\Arguments\ValidationState), Array, NULL, '/var/www/digi/b...', '%message%\nLine:...')
#2 /var/www/digi/b/bugfix-digi-59-exyu-characters-are-not-visible-on/public/vendor/magento/framework/ObjectManager/Factory/Compiled.php(108): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Framewo...', Array)
#3 /var/www/digi/b/bugfix-digi-59-exyu-characters-are-not-visible-on/public/vendor/magento/framework/ObjectManager/ObjectManager.php(56): Magento\Framework\ObjectManager\Factory\Compiled->create('Magento\\Framewo...', Array)
#4 /var/www/digi/b/bugfix-digi-59-exyu-characters-are-not-visible-on/public/vendor/magento/framework/Config/DomFactory.php(42): Magento\Framework\ObjectManager\ObjectManager->create('Magento\\Framewo...', Array)
#5 /var/www/digi/b/bugfix-digi-59-exyu-characters-are-not-visible-on/public/vendor/magento/framework/View/Model/Layout/Update/Validator.php(125): Magento\Framework\Config\DomFactory->createDom(Array)
#6 /var/www/digi/b/bugfix-digi-59-exyu-characters-are-not-visible-on/public/vendor/magento/framework/View/Model/Layout/Merge.php(461): Magento\Framework\View\Model\Layout\Update\Validator->isValid('<layout xmlns:x...', 'layout_merged', false)
#7 /var/www/digi/b/bugfix-digi-59-exyu-characters-are-not-visible-on/public/vendor/magento/framework/View/Model/Layout/Merge.php(442): Magento\Framework\View\Model\Layout\Merge->_validateMergedLayout('LAYOUT_frontend...', '<body>\n   <refe...')
#8 /var/www/digi/b/bugfix-digi-59-exyu-characters-are-not-visible-on/public/vendor/magento/framework/View/Layout/Builder.php(86): Magento\Framework\View\Model\Layout\Merge->load()
#9 /var/www/digi/b/bugfix-digi-59-exyu-characters-are-not-visible-on/public/vendor/magento/framework/View/Layout/Builder.php(63): Magento\Framework\View\Layout\Builder->loadLayoutUpdates()
#10 /var/www/digi/b/bugfix-digi-59-exyu-characters-are-not-visible-on/public/vendor/magento/framework/View/Page/Config.php(197): Magento\Framework\View\Layout\Builder->build()
#11 /var/www/digi/b/bugfix-digi-59-exyu-characters-are-not-visible-on/public/vendor/magento/framework/View/Page/Config.php(207): Magento\Framework\View\Page\Config->build()
#12 /var/www/digi/b/bugfix-digi-59-exyu-characters-are-not-visible-on/public/vendor/magento/framework/View/Result/Page.php(241): Magento\Framework\View\Page\Config->publicBuild()
#13 /var/www/digi/b/bugfix-digi-59-exyu-characters-are-not-visible-on/public/vendor/magento/framework/View/Result/Layout.php(170): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#14 /var/www/digi/b/bugfix-digi-59-exyu-characters-are-not-visible-on/public/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#15 /var/www/digi/b/bugfix-digi-59-exyu-characters-are-not-visible-on/public/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Result\Page\Interceptor->___callParent('renderResult', Array)
#16 /var/www/digi/b/bugfix-digi-59-exyu-characters-are-not-visible-on/public/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
#17 /var/www/digi/b/bugfix-digi-59-exyu-characters-are-not-visible-on/public/generated/code/Magento/Framework/View/Result/Page/Interceptor.php(39): Magento\Framework\View\Result\Page\Interceptor->___callPlugins('renderResult', Array, Array)
#18 /var/www/digi/b/bugfix-digi-59-exyu-characters-are-not-visible-on/public/vendor/magento/framework/App/Http.php(139): Magento\Framework\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#19 /var/www/digi/b/bugfix-digi-59-exyu-characters-are-not-visible-on/public/vendor/magento/framework/App/Bootstrap.php(256): Magento\Framework\App\Http->launch()
#20 /var/www/digi/b/bugfix-digi-59-exyu-characters-are-not-visible-on/public/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#21 {main}

**Expected result:**
The page with full article should be opened

Additional info:
Magento 2.2.0
Croatian language pack
[Magento 2 blog module](https://magefan.com/magento2-blog-extension) by Magefan version: 2.8.6

We upgraded module tolatest version because of problems with croatian characters on Blog category pages, but everything was OK in articles. After upgrading module, the problem with croatian letters on categories is fixed, but for all articles we have this exception error.

We tried to delete all old articles (we though it is some incompatibility), but that didn't help.

**Comment by magefan** [comment]
@cmucovic , thank you for your report.
Please check this article [https://magefan.com/blog/element-block-attribute-class-is-not-accepted-by-the-pattern](https://magefan.com/blog/element-block-attribute-class-is-not-accepted-by-the-pattern)

We believe that this is due to bad layout blog file in your theme. Basycaly you need to find this text
`\Magento\Framework\View\Element\Text\ListText`
in your layouts, and replace it to
`Magento\Framework\View\Element\Text\ListText'
(remove \ at the beggining)

+ dont forget to flush magento cache.

Let us know if this help.

**Comment by Kirtiman-Sigmainfo** [comment]
Hi i am facing a similar problem.

https://magento.stackexchange.com/questions/328062/getting-thos-error-in-my-contactformpage

can you help me solve this? Your solution is not similar to mine,

**Comment by magefan** [comment]
@Kirtiman-Sigmainfo ,

Please follow this article https://magefan.com/blog/element-block-attribute-class-is-not-accepted-by-the-pattern
