### ISSUE TITLE
Error when editing or creating new posts - Element 'htmlContent': This element is not expected. - v2.8.7

### ISSUE THREAD

**Issue by cucoriedka** [magefan/module-blog#225]
I'm getting error when I try to edit of create a new post after updating to the latest version 2.8.7. I've downloaded files from the official website. My version of Magento is 2.1.5.

"Something went wrong while saving this post. Element 'htmlContent': This element is not expected. Expected is one of ( container, fieldset, field, insertForm, insertListing, modal, button, dynamicRows ). Line: 367"

Has anyone experienced this problem and has solution to this? @magefan

**Comment by cucoriedka** [comment]
SOLVED - 

Comment out htmlContent section in view/adminhtml/ui_component/blog_post_form.xml

This is because I'm using Magento 2.1 version. 
For more instruction, read (https://github.com/magefan/module-blog/commit/f46a813249c884126d747a623a89abfb656f94af)

**Comment by magefan** [comment]
@cucoriedka , please use this fix 
https://github.com/magefan/module-blog/commit/325f309c4b503100ca32add3e65c5989252696bc

**Comment by magefan** [comment]
Let me know if this fix works for you on Magento2.1 and Blog 2.8.7

**Comment by cucoriedka** [comment]
@magefan Thank you, this fixed worked!
