### ISSUE TITLE
Featured Images

### ISSUE THREAD

**Issue by Krapulat** [magefan/module-blog#23]
Hello,

The featured images doesn't appear in post list. Why?

**Comment by magefan** [comment]
@Krapulat 
1. After update post try to refresh magento cache
2. Check if your template files in extension folder and theme (if they are overridden) includes code $_post->getFeaturedImage(). If not update your template files
This is last original files:
https://github.com/magefan/module-blog/blob/master/view/frontend/templates/post/view.phtml
https://github.com/magefan/module-blog/blob/master/view/frontend/templates/post/list/item.phtml

**Comment by Krapulat** [comment]
@magefan Thanks. It works! The Porto theme had overridden these files.

**Comment by refaelgold** [comment]
Put notice thats a lot of themes who is this GREAT extension and when you upgrade , you must modify the duplicate phtml files inside .
