### ISSUE TITLE
No ImageUploadConfig backend error in Magento 2.2.8

### ISSUE THREAD

**Issue by Tomasz-Silpion** [magefan/module-blog#235]
\Magefan\Blog\Block\Adminhtml\Post\Helper\Form\Gallery class throws "Class Magento\Backend\Block\DataProviders\ImageUploadConfig does not exist" error causing:

`Method Magento\Ui\TemplateEngine\Xhtml\Result::__toString() must not throw an exception, caught Error: Call to a member function getIsResizeEnabled()`

It looks like, at least under some circumstances Magefan_Blog is not compatible with Magento Community 2.2.8 edition.

One fix was suggested by @ubermanu in https://github.com/magefan/module-blog/pull/234 but I believe that such approach would break the plugin again in 2.3.0 and later as the UploadConfig class was renamed to ImageUploadConfig. Compare:

https://github.com/magento/magento2/tree/2.2/app/code/Magento/Backend/Block/DataProviders

https://github.com/magento/magento2/tree/2.3/app/code/Magento/Backend/Block/DataProviders

**Comment by ubermanu** [comment]
I'm not sure about your change as well
The exception was supposed to be thrown for older magento versions (see line 49)
One way to fix this would be to check for the magento 2 version, and load the according class
or to create separated release branches, for magento 2.2.X and magento 2.3.X
