### ISSUE TITLE
Typo in blog_category_edit.xml

### ISSUE THREAD

**Issue by chris-brabender** [magefan/module-blog#24]
This is just a minor issue but shows up in the static code tests but in the file

    view/adminhtml/layout/blog_category_edit.xml

The NamespaceSchemaLocation references a .xsd that doesn't exist, it appears a / was missed

    xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etcpage_configuration.xsd">

should probably  be

    xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">

**Comment by magefan** [comment]
@chris-brabender, thank you very much. It's fixed (https://github.com/magefan/module-blog/commit/e9c9bc6bf4d3179e02bd51af93a9965f85641cdb)
