### ISSUE TITLE
Widget Blog Post List not working properly

### ISSUE THREAD

**Issue by afavata** [magefan/module-blog#242]
Magento 2.3.1
Php 7.2.15
Magefan Blog 2.8.9

Issue when trying to add the widget "Magefan Blog Post List" to a content/block:
no parameters are shown to configure widget behaviour.

See image herewith
<img width="1280" alt="2019-04-22" src="https://user-images.githubusercontent.com/15713756/56499145-62e61b00-6505-11e9-95f5-d72701657e59.png">

**Comment by magefan** [comment]
@afavata , if you will check the original Magefan Blog code, you will see that there is no "Magefan Blog Posts List" widget there https://github.com/magefan/module-blog/blob/master/etc/widget.xml
By default, we offer only these widgets:
 - Recent Blog Posts
 - Featured Blog Posts

I think that "Magefan Blog Posts List" widget is some customization you have, or it comes to you with your theme. I recommend you to contact modification provider to solve the issue or you can try just to scroll down to see if any button will be available for you.

**Comment by afavata** [comment]
Thanks ... I will double check this
