### ISSUE TITLE
Compilation error : Class 'Magefan\BlogPlus\Plugin\Block\Adminhtml\AbstractPublishedSaveButtonPlugin' not found

### ISSUE THREAD

**Issue by yanncharlou** [magefan/module-blog#245]
Compilation error with :
name": "magefan/module-blog",
"version": "2.8.9.1",
magento : 2.2.8

PHP Fatal error:  Class 'Magefan\BlogPlus\Plugin\Block\Adminhtml\AbstractPublishedSaveButtonPlugin' not found in /var/www/clients/client1/web1/web/releases/20190514105119/vendor/magefan/module-blog/Plus/Plugin/Block/Adminhtml/Post/PublishedSaveButtonPlugin.php on line 15

Bug found only in 2.8.9.1. Compilation is ok with "magefan/module-blog" 2.8.9.

**Comment by magefan** [comment]
@yanncharlou , this issue section is only for the Blog Standard. If you have any issue with the Blog Plus or Blog Extra, please contact Magefan Support via the email support@magefan.com and provide your Magefan Order ID.

**Comment by yanncharlou** [comment]
I'm not using Blog plus, but Blog Standard only.
Installed by composer. module used : "magefan/module-blog": "^2.8",

composer update yesterday as made this change in my composer.lock :
```
{
             "name": "magefan/module-blog",
-            "version": "2.8.8",
+            "version": "2.8.9.1",
             "dist": {
                 "type": "zip",
-                "url": "https://magefan.com/repo/packages/download/id/79/",
+                "url": "https://magefan.com/repo/packages/download/id/122/",
                 "reference": null,
                 "shasum": null
             },
@@ -1718,12 +1684,12 @@
         },
```
reverting to "magefan/module-blog": "2.8.9", seems allow me getting back Blog Standard Only.

I've never found a bug like that. Some mistake in repository ?
My original composer.json require section : (nothing from magefan in app/code)
    "require": {
        "magento/product-community-edition": "2.2.8",
        "composer/composer": "@alpha",
        "firegento/fastsimpleimport": "^1.1",
        "league/csv": "^9.1",
        "xtento/orderexport": "^2.6",
        "mageplaza/module-delete-orders": "^1.1",
        "imaginaerum/magento2-language-fr-fr": "*",
        "owebia/magento2-module-advanced-shipping-setting": "^2.1.1",
        "shoppingfeed/magento2-manager": "@dev",
        "magenizr/magento2-resetuibookmarks": "1.0.0",
        "magekey/module-adc-popup": "2.0.6",
        "amasty/shopby": "^2.10",
        "olegkoval/magento2-regenerate-url-rewrites": "^1.3",
        "compactcode/fixproductbreadcrumbs": "dev-master",
        "magefan/module-blog": "^2.8",
        "magepal/magento2-gmailsmtpapp": "^2.6",
        "maxserv/magento-module-yoastseo": "^2.0",
        "weltpixel/module-google-tag-manager": "^1.6"
    },

**Comment by magefan** [comment]
There should be BlogPlus in your store or in the customizations. Please try to look for "BlogPlus" string in your code. If you will check original Blog Standard extension code, there is no mention about BlogPlus
https://github.com/magefan/module-blog/search?q=BlogPlus&type=Code

**Comment by yanncharlou** [comment]
with module-blog 2.8.9 installed and nothing related to BlogPlus :

# installing ou updating based on module-blog ^2.8 :

```
composer require magefan/module-blog ^2.8
./composer.json has been updated                                                             
Loading composer repositories with package information
Updating dependencies (including require-dev)                                                
Package operations: 0 installs, 1 update, 0 removals
  - Updating magefan/module-blog (2.8.9 => 2.8.9.1): Loading from cache
Package fabpot/php-cs-fixer is abandoned, you should avoid using it. Use friendsofphp/php-cs-fixer instead.
Package owebia/magento2-module-advanced-shipping-setting is abandoned, you should avoid using it. Use owebia/magento2-module-advanced-shipping instead.
Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.
Writing lock file
Generating autoload file
```

And this directory appear : magento2/vendor/magefan/module-blog/Plus directory that seems containing BlogPlus files.

# reverting to 2.8.9 :

```
composer require magefan/module-blog 2.8.9
./composer.json has been updated                                                             
Loading composer repositories with package information
Updating dependencies (including require-dev)                                                
Package operations: 0 installs, 1 update, 0 removals
  - Updating magefan/module-blog (2.8.9.1 => 2.8.9): Loading from cache
Package fabpot/php-cs-fixer is abandoned, you should avoid using it. Use friendsofphp/php-cs-fixer instead.
Package owebia/magento2-module-advanced-shipping-setting is abandoned, you should avoid using it. Use owebia/magento2-module-advanced-shipping instead.
Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.
Writing lock file
Generating autoload files
```
And this directory disappear : magento2/vendor/magefan/module-blog/Plus

**Comment by magefan** [comment]
We have double check, and the issue was in an archive in our composer repository server. Now please run these commands
composer remove magefan/module-blog
composer clear
composer require magefan/module-blog

Let me know if it works for you

Regards,
Ihor

**Comment by yanncharlou** [comment]
Hi Ihor,

Problem solved. :-)

Best regards,
Yann
