### ISSUE TITLE
After add buttom "Add New Post"

### ISSUE THREAD

**Issue by sarootua** [magefan/module-blog#254]
Magento 2.3.1 After add buttom "Add New Post" 

PHP message: PHP Fatal error:  Method Magento\Ui\TemplateEngine\Xhtml\Result::__toString() must not throw an exception, caught Error: Call to a member function getIsResizeEnabled() on null in /site.com/public_html/vendor/magento/module-ui/Component/Wrapper/UiComponent.php on line 0" while reading response header from upstream, client: IP, server: site.com, request: "GET /admin/blog/post/edit/id/1/ HTTP/2.0", upstream: "fastcgi://127.0.0.1:9001", host: "site.com", referrer: "https://site.com/admin/blog/post/"

**Comment by magefan** [comment]
@sarootua , thank you for your report. Please make sure that you use the latest blog v2.8.10. 
Here you can find [Magento 2 Blog updating instructions](https://magefan.com/blog/update-magefan-blog-extension).


Let us know if you already have this issue on v2.8.10.

**Comment by sarootua** [comment]
Thanks! Works)

**Comment by magefan** [comment]
@sarootua , could I as you please to [leave your honest feedback](https://magefan.com/magento2-blog-extension/reviews#review-form) about the [Magento 2 Blog](https://magefan.com/magento2-blog-extension) extension ?
