### ISSUE TITLE
Version - 2.8.10 -Error During Compilation

### ISSUE THREAD

**Issue by pioneerathletics** [magefan/module-blog#258]
Hi,
I'm having an issue during compilation, after upgrading to blog version 2.8.10. I am running Magento 2.1.17

Here is the compilation error:

`Errors during compilation:
	Magefan\Blog\Block\Adminhtml\System\Config\Form\CheckEnableInfo
		Incorrect dependency in class Magefan\Blog\Block\Adminhtml\System\Config\Form\CheckEnableInfo in /srv/public_html/app/code/Magefan/Blog/Block/Adminhtml/System/Config/Form/CheckEnableInfo.php
\Magento\Store\Model\StoreManagerInterface already exists in context object
Total Errors Count: 1
Errors during compilation:
	Magefan\Blog\Block\Adminhtml\System\Config\Form\CheckEnableInfo
		Incorrect dependency in class Magefan\Blog\Block\Adminhtml\System\Config\Form\CheckEnableInfo in /srv/public_html/app/code/Magefan/Blog/Block/Adminhtml/System/Config/Form/CheckEnableInfo.php
\Magento\Store\Model\StoreManagerInterface already exists in context object
Total Errors Count: 1
Errors during compilation:
	Magefan\Blog\Block\Adminhtml\System\Config\Form\CheckEnableInfo
		Incorrect dependency in class Magefan\Blog\Block\Adminhtml\System\Config\Form\CheckEnableInfo in /srv/public_html/app/code/Magefan/Blog/Block/Adminhtml/System/Config/Form/CheckEnableInfo.php
\Magento\Store\Model\StoreManagerInterface already exists in context object
Total Errors Count: 1
Errors during compilation:
	Magefan\Blog\Block\Adminhtml\System\Config\Form\CheckEnableInfo
		Incorrect dependency in class Magefan\Blog\Block\Adminhtml\System\Config\Form\CheckEnableInfo in /srv/public_html/app/code/Magefan/Blog/Block/Adminhtml/System/Config/Form/CheckEnableInfo.php
\Magento\Store\Model\StoreManagerInterface already exists in context object
Total Errors Count: 1
Errors during compilation:
	Magefan\Blog\Block\Adminhtml\System\Config\Form\CheckEnableInfo
		Incorrect dependency in class Magefan\Blog\Block\Adminhtml\System\Config\Form\CheckEnableInfo in /srv/public_html/app/code/Magefan/Blog/Block/Adminhtml/System/Config/Form/CheckEnableInfo.php
\Magento\Store\Model\StoreManagerInterface already exists in context object
Total Errors Count: 1
Errors during compilation:
	Magefan\Blog\Block\Adminhtml\System\Config\Form\CheckEnableInfo
		Incorrect dependency in class Magefan\Blog\Block\Adminhtml\System\Config\Form\CheckEnableInfo in /srv/public_html/app/code/Magefan/Blog/Block/Adminhtml/System/Config/Form/CheckEnableInfo.php
\Magento\Store\Model\StoreManagerInterface already exists in context object
Total Errors Count: 1
Errors during compilation:
	Magefan\Blog\Block\Adminhtml\System\Config\Form\CheckEnableInfo
		Incorrect dependency in class Magefan\Blog\Block\Adminhtml\System\Config\Form\CheckEnableInfo in /srv/public_html/app/code/Magefan/Blog/Block/Adminhtml/System/Config/Form/CheckEnableInfo.php
\Magento\Store\Model\StoreManagerInterface already exists in context object
Total Errors Count: 1
Errors during compilation:
	Magefan\Blog\Block\Adminhtml\System\Config\Form\CheckEnableInfo
		Incorrect dependency in class Magefan\Blog\Block\Adminhtml\System\Config\Form\CheckEnableInfo in /srv/public_html/app/code/Magefan/Blog/Block/Adminhtml/System/Config/Form/CheckEnableInfo.php
\Magento\Store\Model\StoreManagerInterface already exists in context object
Total Errors Count: 1
Errors during compilation:
	Magefan\Blog\Block\Adminhtml\System\Config\Form\CheckEnableInfo
		Incorrect dependency in class Magefan\Blog\Block\Adminhtml\System\Config\Form\CheckEnableInfo in /srv/public_html/app/code/Magefan/Blog/Block/Adminhtml/System/Config/Form/CheckEnableInfo.php
\Magento\Store\Model\StoreManagerInterface already exists in context object
Total Errors Count: 1
Errors during compilation:
	Magefan\Blog\Block\Adminhtml\System\Config\Form\CheckEnableInfo
		Incorrect dependency in class Magefan\Blog\Block\Adminhtml\System\Config\Form\CheckEnableInfo in /srv/public_html/app/code/Magefan/Blog/Block/Adminhtml/System/Config/Form/CheckEnableInfo.php
\Magento\Store\Model\StoreManagerInterface already exists in context object
Total Errors Count: 1
Errors during compilation:
	Magefan\Blog\Block\Adminhtml\System\Config\Form\CheckEnableInfo
		Incorrect dependency in class Magefan\Blog\Block\Adminhtml\System\Config\Form\CheckEnableInfo in /srv/public_html/app/code/Magefan/Blog/Block/Adminhtml/System/Config/Form/CheckEnableInfo.php
\Magento\Store\Model\StoreManagerInterface already exists in context object
Total Errors Count: 1`

**Comment by magefan** [comment]
Hello @pioneerathletics , thank you for your report. This is a known issue and has already been fixed https://github.com/magefan/module-blog/commit/11688dfb0a22d34b5f1f0d0a5c01d44832fc6e64. It will be included in the next [Magento 2 Blog](https://magefan.com/magento2-blog-extension) v2.9.0.

Let us know if the fix woks well for you.

**Comment by pioneerathletics** [comment]
Hi @magefan,

I was able to successfully compile, but when trying to access from the admin I'm getting another error: 

![Screen-Shot-2019-07-02-at-10 11 54-AM](https://user-images.githubusercontent.com/19981272/60520160-e7e27300-9cb2-11e9-8fe2-82c4e8cc16f1.jpg)

**Comment by magefan** [comment]
@pioneerathletics ,

1. What Magento version do you have?
2. What page in the admin panel do you try to access?

**Comment by pioneerathletics** [comment]
@magefan,

1. Magento version 2.1.17
2. Content>Blog>Posts or any blog related menu item within the Content tab

**Comment by pioneerathletics** [comment]
@magefan ,

I recopied the file you linked to above 11688df, cleared all generated code, recompiled, cleared all caches and it seems to have fixed the issue. I can view Content>Blog>Posts successfully. Thanks!
