### ISSUE TITLE
  Class Magento\Ui\Block\Wysiwyg\ActiveEditor does not exist  

### ISSUE THREAD

**Issue by im-dnsosso** [magefan/module-blog#261]
Class Magento\Ui\Block\Wysiwyg\ActiveEditor does not exist  
during DI compile. The file does not exists in Magento 2.2.*

**Comment by Stevie-Ray** [comment]
Hi Magefan, I can confirm this doesn't work

**Comment by magelife** [comment]
Also confirmed. Composer forces install of this additional module, and the class doesn't exist in Magento 2.2, breaking the entire blog.

**Comment by magelife** [comment]
Just confirmed a temporary fix for you guys if you're still having trouble with this: v 2.8.10 does NOT require the wysiwyg. 
See dependencies here:
https://packagist.org/packages/magefan/module-blog#2.8.10

If you change ^2.9.0 in composer.json to 2.8.10 and re-run composer update it should work with Magento 2.2.*. Don't forget to change the version number accordingly in the setup_module table to avoid an exception error.

**Comment by magefan** [comment]
@Stevie-Ray , @magelife, @im-dnsosso.

Thank you for your report.

This issue happens only on Magento 2.1.x and 2.2.x in module [Magefan_WysiwygAdvanced](https://github.com/magefan/module-wysiwyg-advanced) that was created to extend [Magento 2.3 WYSIWYG ](https://magefan.com/blog/magento-2.3-tinymce-4-text-color-tool-missing).

As a temporary solution, please disable this module. Run the command:

`bin/magento module:disable Magefan_WysiwygAdvanced`

**Comment by magefan** [comment]
Please try this permanent fix 
https://github.com/magefan/module-wysiwyg-advanced/commit/4a0a50aa97c25ab9477bde09755369419d04f519

Let us know if it works well for you.

**Comment by magefan** [comment]
If you update the blog extension to v2.9.0.1 via the composer, the issue will be automatically fixed.

**Comment by im-dnsosso** [comment]
Hi Sorry for the late reply. Yes It's working!!! Thank you for the quick fix
