### ISSUE TITLE
Unwanted comma at end of line 182 en_US.csv

### ISSUE THREAD

**Issue by Alphaws** [magefan/module-blog#262]
https://github.com/magefan/module-blog/blob/ee55e54f3dc11b8a32ac758417e4da705c634d92/i18n/en_US.csv#L182

**Comment by magefan** [comment]
@Alphaws , thank you for your report. We have fixed it https://github.com/magefan/module-blog/commit/964c06785a59468037af0d18c5a25198a6b01f32, this changes will be included in the next release.
