### ISSUE TITLE
Publish Date in comments is not saved in proper format

### ISSUE THREAD

**Issue by wintermute-84** [magefan/module-blog#265]
When validating (saving) a comment in admin, date picker sends date and time in ISO 8601 format
![Screenshot 2019-08-12 at 14 29 20](https://user-images.githubusercontent.com/3521295/62859691-e9ba4000-bd0e-11e9-9bc2-2d4a4400b618.png)

Magefan\Blog\Controller\Adminhtml\Comment\Save::filterParams() is trying to filter it, but fails to convert it properly and it is saved to the database as 0000-00-00 00:00:00

**Comment by magefan** [comment]
@wintermute-84 , can you tell me what locale do you use in your Magento admin panel?

**Comment by magefan** [comment]
Ticket closed due to inactivity.
