### ISSUE TITLE
new release with configurable topmenu item

### ISSUE THREAD

**Issue by davidverholen** [magefan/module-blog#27]
Hey,

would it be possible that you make a new release with the new config whether to show the blog in the topmenu? We would need this for a project.

thx in advance!

**Comment by PhiIipp** [comment]
Good idea,  i have also a question. Where do i change the label of the current top level enty ? Want to change from Blog to BLOG. Footer label config found but no top navi. 

Thx
Philipp

**Comment by magefan** [comment]
Sorry for the long delay. New version (2.2.2) is now available.

@PhiIipp you can find this configurations in Stores > Configuration > Blog > Category Top Navigation
