### ISSUE TITLE
Uncaught TypeError: $(...).colpick is not a function error in store configuration

### ISSUE THREAD

**Issue by DuckThom** [magefan/module-blog#285]
When going to the store configuration of the module, the following message is shown in the DevTools console and it's breaking the JS on the whole page.

```
(index):643 Uncaught TypeError: $(...).colpick is not a function
    at (index):643
    at Object.execCb (require.js:1650)
    at Module.check (require.js:866)
    at Module.<anonymous> (require.js:1113)
    at require.js:132
    at require.js:1156
    at each (require.js:57)
    at Module.emit (require.js:1155)
    at Module.check (require.js:917)
    at Module.enable (require.js:1143)
```

It's being caused by the following line, removing it also removes the error in the console: https://github.com/magefan/module-blog/blob/bacd04f04e0da3b8768e5a4e634eb5c4e497ed3f/Block/Adminhtml/System/Config/Form/ColorPicker.php#L31

The site is running Magento 2.3.3 Commerce edition.

After some digging, it looks like 'colpick' is provided by the Dotdigitalgroup_Email magento 2 module which we have disabled. I would suggest to use the js module `jquery/colorpicker/js/colorpicker` which is provided by Magento itself

**Comment by magefan** [comment]
We have merged your code to [Magento 2 Blog](https://magefan.com/magento2-blog-extension). We will add some additional improvements for the color picker and release the new version 2.9.1.1 asap.

**Comment by magefan** [comment]
v2.9.1.1 with additional changes is now available
