### ISSUE TITLE
Issue Updating to 2.9.1.2

### ISSUE THREAD

**Issue by pioneerathletics** [magefan/module-blog#293]
- Magento 2.3.3
- Updated to latest [Magento Blog](https://magefan.com/magento2-blog-extension) 2.9.1.2

I manually update Magefan/Blog to the latest version. When running setup:upgrade I get this error:
`Schema creation/updates:
Notice: Undefined index: magefan_blog_post in /srv/main_folder/vendor/magento/framework/Setup/Declaration/Schema/Db/SchemaBuilder.php on line 152`

**Comment by magefan** [comment]
@pioneerathletics , please try to flush magento cache

bin/magento c:f

also try to remove var/cache and generated

Let us know if this helps
