### ISSUE TITLE
Autocomplete CSS break the default UI elements styling

### ISSUE THREAD

**Issue by coughsyrupgit** [magefan/module-blog#298]
Hi!

[Magento 2 Blog](https://magefan.com/magento2-blog-extension) version - 2.9.1
Magento version - 2.3.3

On the Post Edit page in adminhtml area there is the autocomplete.css file included. Some of its styles break the default UI components styling, such as a datepicker. See the example screenshot:

![Screenshot of the issue](https://i.imgur.com/cLU0YjV.png)

The correct view of a datepicker is following:
![Correct view of a datepicker](https://i.imgur.com/5F7QQEB.png)

**Comment by ihorvansach** [comment]
Thank you @coughsyrupgit for your report. 
Please use this fix https://github.com/magefan/module-blog/commit/29cf2444cdfcbef3ec602103520143c2c63a5f35

File after changes
https://raw.githubusercontent.com/magefan/module-blog/master/view/adminhtml/web/css/autocomplete.css

Please let us know if it works well for you.

**Comment by coughsyrupgit** [comment]
Wow, thanks @ihorvansach for such a lightning-speed response!

Yep, that fixed the issue. Much thanks and have a good day!

**Comment by ihorvansach** [comment]
You're welcome @coughsyrupgit , don't forget to press star on magefan/module-blog repository ;-)
