### ISSUE TITLE
Http error 500 / PHP fatal error on blog posts pages

### ISSUE THREAD

**Issue by Vikwip** [magefan/module-blog#304]
Hello,

I get http errors 500 and php fatal errors in my log while going to single posts pages, e.g. ==> `blog.html/post/post-title` on my local magento installation.

### Preconditions

1. Magento: 2.3.3-p1 (mode: developer)
2. Blog Extension v2.9.1 
3. PHP: 7.2.26 
4. Nginx 1.10.3
5. MySQL: 5.7.28-31
6. [Magento Developer Box](https://github.com/zepgram/magento2-fast-vm) with Vagrant 2.2.6 and 
Linux Debian 9 (stretch)

### Actual result
Nginx error log:

` *6147 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Cannot instantiate interface Magefan\Blog\Api\UrlResolverInterface in /home/vagrant/magento/magento2/vendor/magento/fra$Stack trace:`

`#0 /home/vagrant/magento/magento2/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magefan\\Blog\\Ap...')`

`#1 /home/vagrant/magento/magento2/vendor/magefan/module-blog/Controller/Router.php(132): Magento\Framework\ObjectManager\ObjectManager->get('Magefan\\Blog\\Ap...')`

`#2 /home/vagrant/magento/magento2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(116): Magefan\Blog\Controller\Router->__construct(Object(Magento\Framework\App\ActionFactory), Object(Magento\Staging\Model\Event\Manag$`

Could you please help me to fix this error? 
Thanks!

**Comment by ihorvansach** [comment]
@Vikwip , please update blog extension to the latest v2.9.2.1 , let us know if it helps.

**Comment by Vikwip** [comment]
Hello Ihor,
The post pages are working now. I actually didn't update the extension yet but I changed my full page cache config in stores configuration from Fastly CDN to Built-in-cache.

**Comment by ihorvansach** [comment]
@Vikwip , can we close the ticket?

**Comment by Vikwip** [comment]
@ihorvansach , yes I close it.
