### ISSUE TITLE
Hi team. I am facing with problem when migrate blog from Wordpress to Magento 2

### ISSUE THREAD

**Issue by MartinNguyen211** [magefan/module-blog#305]
when I try migrate blog from Wordpress to [Magento 2 Blog](https://magefan.com/magento2-blog-extension)
- In  Wordpress content like this

[caption id="attachment_4632" align="alignright" width="270"]

- And when in blog page. this content was progress to like this

figure id="attachment_4632" style="max-width: 270px" class="wp-caption alignright"

=> can we do this one in this module?

**Comment by ihorvansach** [comment]
@MartinNguyen211 , can you confirm that your Magento instance has this fix for the blog extension https://github.com/magefan/module-blog/commit/3e9a6a1c3ab40ef82f20f9c9ce95201a932ecfbd ?

**Comment by MartinNguyen211** [comment]
thanks @ihorvansach

**Comment by magefan** [comment]
@MartinNguyen211 , is your issue fixed?

**Comment by MartinNguyen211** [comment]
@magefan I fix already. thank you
