### ISSUE TITLE
about convert Blog To PDF

### ISSUE THREAD

**Issue by MartinNguyen211** [magefan/module-blog#308]
Hi team. do we have function convert blog page to PDF in the [Magento 2 Blog Extension](https://magefan.com/magento2-blog-extension)?

**Comment by ihorvansach** [comment]
Hello @MartinNguyen211 ,

No, we don't have such a feature. What I can suggest is 
1. To add a print button, use JS window.print()  as it's action
2. Include special CSS only for the print view for the blog pages

In this way, the visitor will be able to save the page into PDF

**Comment by MartinNguyen211** [comment]
yes. I see. thanks @ihorvansach
