### ISSUE TITLE
Error updating on Magento 2.3.4

### ISSUE THREAD

**Issue by pioneerathletics** [magefan/module-blog#310]
Magento version 2.3.4
[Magento Blog](https://magefan.com/magento2-blog-extension) by Magefan version - 2.9.2.1
Installation method - manually over sftp

I'm receiving this error after running setup:upgrade.
Schema creation/updates:
Notice: Undefined index: magefan_blog_post in /srv/public_html/vendor/magento/framework/Setup/Declaration/Schema/Db/SchemaBuilder.php on line 152

Please advise.

Thank you,

Dave

**Comment by ihorvansach** [comment]
@pioneerathletics , this looks like some Magento issue.
Please check this article for more information

1. https://community.magento.com/t5/Magento-2-x-Version-Upgrades/Undefined-index-sales-shipment-Error-When-upgrading-from-2-2-4/td-p/120530
2. https://magento.stackexchange.com/questions/275660/magento-2-error-undefined-index-while-upgrading-m-2-2-5-m-2-3-1
3. https://www.google.com/search?q=magento+2+Notice%3A+Undefined+index+SchemaBuilder.php+on+line+152

Looks like your database was corupted and table magefan_blog_post does not exists. Try to restore it from the backup.
