### ISSUE TITLE
MageFan Blog Support for PageBuilder

### ISSUE THREAD

**Issue by duffner** [magefan/module-blog#318]
Team, 

It appears that Magento Commerce Edition PageBuilder breaks comments introduced by your extension which provides support for excerpts, can you take a look.  I'll gladly provide more information if it's not clear

**Comment by ihorvansach** [comment]
@duffner , yes, we will take a look, please provide more details on how we can reproduce this issue.

**Comment by ihorvansach** [comment]
@duffner , is the issue still there?
