### ISSUE TITLE
2.3.5 Console error

### ISSUE THREAD

**Issue by nadroj467** [magefan/module-blog#320]
Hi,

After upgrading to Magento 2.3.5-p1 we are getting the below error in console when trying to run the bin/magento setup:upgrade command. We have updated to latest 2.9.3 Blog version

Warning: Declaration of Magefan\Blog\Model\ImageUploader::moveFileFromTmp($imageName) should be compatible with Magento\Catalog\Model\ImageUploader::moveFileFromTmp($imageName, $returnRelativePath = false) in /home/domain/public_html/vendor/magefan/module-blog/Model/ImageUploader.php on line 108

Thanks

**Comment by ihorvansach** [comment]
@nadroj467 , please use this fix

**Comment by luckyraul** [comment]
@ihorvansach release the fix please

**Comment by magefan** [comment]
v2.9.4 released
