### ISSUE TITLE
Problems after uninstalling the module

### ISSUE THREAD

**Issue by in-session** [magefan/module-blog#324]
<br />
<b>Warning</b>:  require(/html/magento2/vendor/composer/../magefan/module-community/registration.php): failed to open stream: No such file or directory in <b>/html/magento2/vendor/composer/autoload_real.php</b> on line <b>73</b><br />
<br />
<b>Warning</b>:  require(/html/magento2/vendor/composer/../magefan/module-wysiwyg-advanced/registration.php): failed to open stream: No such file or directory in <b>/html/magento2/vendor/composer/autoload_real.php</b> on line <b>73</b><br />
<br />
<b>Warning</b>:  require(/html/magento2/vendor/composer/../magefan/module-blog/registration.php): failed to open stream: No such file or directory in <b>/html/magento2/vendor/composer/autoload_real.php</b> on line <b>73</b><br />
1 exception(s):
Exception #0 (Magento\Framework\Exception\FileSystemException): The contents from the "/html/magento2/vendor/magefan/module-community/etc/module.xml" file can't be read. Warning!file_get_contents(/html/magento2/vendor/magefan/module-community/etc/module.xml): failed to open stream: No such file or directory

Exception #0 (Magento\Framework\Exception\FileSystemException): The contents from the "/html/magento2/vendor/magefan/module-community/etc/module.xml" file can't be read. Warning!file_get_contents(/html/magento2/vendor/magefan/module-community/etc/module.xml): failed to open stream: No such file or directory

**Comment by magefan** [comment]
@in-session , looks like you just manually removed vendor/magefan folder.
Please follow the uninstallation instructions 
https://magefan.com/blog/uninstall-magefan-blog-extension
