### ISSUE TITLE
Remove root "Blog" from category urls

### ISSUE THREAD

**Issue by Catlon** [magefan/module-blog#33]
Hello,

How can we **rename the "Blog" index page title** displayed in the navbar and breadcrumbs ?

I've changed it to "news" in the extension settings page, but its only reflecting the change in the urls.

Thank you,
Cyril

**Comment by magefan** [comment]
@Catlon  you can remove blog from category urls in Stores > Configuration > Blog > Category Top Navigation > Display Blog Link set to "YES". If you do not have such option, please update blog extension to the latest version.

To change "Blog" title to "News", please use inline translate functionality of M2 (http://docs.magento.com/m2/ee/user_guide/system/translate-inline.html)

**Comment by Catlon** [comment]
Ok thank you for this.

**Comment by sanganagouda1** [comment]
hi i want to change blog extension url from  "http://magento2/blog/post/post-name/" to 
so i want to change url like  "http://www.magento2/post-name/    or http://www.magento2/news/new/post-name/  ??

**Comment by sanganagouda1** [comment]
how to change url blog to news ???

**Comment by magefan** [comment]
Please navigate to Stores > Configuration > Blog > Permalink Settings to change this.
