### ISSUE TITLE
Datepicker bug for Dutch language setting

### ISSUE THREAD

**Issue by cdekkers** [magefan/module-blog#330]
I noticed that the publish date of a blog post gets displayed incorrectly after saving it from the datepicker in the admin area, and if the user's language is set to Dutch.

To replicate the issue, please set your interface language to Dutch under account settings, and navigate to a blog post. Setting the publish date to today (2020-07-21), for example, will save the date correctly, as can be seen from the blog post grid. In the datepicker, however, the publish date will be shown as 2021-07-20 — i.e. the year and day are swapped. Continuously saving the post (for example, because you are making incremental edits) will continue to set and display the date incorrectly. E.g. 2019-07-01 will display as 2001-07-20, then 2020-07-20. The year and day are now both 20 so swapping from this point has no effect.

I hope you can look into this issue. I can imagine that people using other language settings might also be affected by it.

**Comment by magefan** [comment]
@cdekkers , could you please try this fix https://github.com/magefan/module-blog/commit/e8003a5fa8c621cf1fbbe4614221c9865f45b831 ? Let us know if it works well for you.

**Comment by cdekkers** [comment]
Thanks for your swift reply. I'll try the fix and will then let you know whether it resolves the issue.

**Comment by magefan** [comment]
@cdekkers , does the fix fork for you well?

**Comment by cdekkers** [comment]
Unfortunately, it does not seem to work for me. Maybe it's because the problem I describe is actually slightly different from the problem that is addressed by your fix:

> There's a problem with the Publish Date box when saving or updating a post in Admin. When selecting a date from the date picker for locale English Australia, the date is saved in American format. For example, selecting 1 June 2020 from the date picker the post publish date is saved as January 6 2020. To save as 1 June 2020 you have to manually enter it in the box in American format - 06/01/2020.

The problem I have is very similar, the only difference with the description above is that the date appears to be saved correctly, but is rendered incorrectly in the date picker.

To reproduce:

1. Set your account locale to Dutch (might also be an issue in other languages, though).
2. Browse to a blog post and edit the date.
3. In the example below, I set the publish date to 17 January 2020. Most dates (including this one) but not all will trigger the issue.
4. Save the post. In the blog post grid, it appears to have saved the date correctly.
5. Reopen the blog post. The date is now represented as 20 January 2017.

Saving the post again (not shown) will actually overwrite the date and set it to 20 January 2017. Reopening the post again will show the date as 20 January 2020 (which, if saved again, will not change anymore).

![magefan_blog_date_format_bug](https://user-images.githubusercontent.com/5476946/89559734-5da20200-d816-11ea-8dfd-1e52a34d473f.gif)

**Comment by kennethbonte** [comment]
I managed to fix this by changing magefan/module-blog/Ui/DataProvider/Post/Form/PostDataProvider.php
Adjusting the publish time to the current interface locale. Didn't have the time to put in a pull request yet. Can you verify first?

```
...
/**
     * @var \Magento\Framework\Stdlib\DateTime\DateTimeFormatterInterface
     */
    protected $dateTimeFormatter; // changes
    /**
     * @var \Magento\Backend\Model\Locale\Manager
     */
    protected $localeManager; // changes
    /**
     * @param string $name
     * @param string $primaryFieldName
     * @param string $requestFieldName
     * @param CollectionFactory $postCollectionFactory
     * @param DataPersistorInterface $dataPersistor
     * @param array $meta
     * @param array $data
     */
    public function __construct(
        $name,
        $primaryFieldName,
        $requestFieldName,
        CollectionFactory $postCollectionFactory,
        DataPersistorInterface $dataPersistor,
        \Magento\Framework\Stdlib\DateTime\DateTimeFormatterInterface $dateTimeFormatter, // changes
        \Magento\Backend\Model\Locale\Manager $localeManager, // changes
        array $meta = [],
        array $data = []
    ) {
        $this->collection = $postCollectionFactory->create();
        $this->dataPersistor = $dataPersistor;
        $this->dateTimeFormatter = $dateTimeFormatter; // changes
        $this->localeManager = $localeManager; // changes
        parent::__construct($name, $primaryFieldName, $requestFieldName, $meta, $data);
        $this->meta = $this->prepareMeta($this->meta);
    }

...

            $data['data']['links']['product'] = $items;

            // Changes
            // Adjust publish_time according to interface locale
            $staticDate = new \DateTime($data['publish_time']);
            $currentLocaleCode = $this->localeManager->getUserInterfaceLocale();
            $data['publish_time'] = $this->dateTimeFormatter->formatObject($staticDate, \IntlDateFormatter::SHORT, $currentLocaleCode);
            // End changes

            /* Set data */
            $this->loadedData[$post->getId()] = $data;

...
