### ISSUE TITLE
Error uploading Feautured Image on magento 2.4.0

### ISSUE THREAD

**Issue by karpa** [magefan/module-blog#337]
Magento 2.4.0
module-blog 2.9.6.1

Upalodaing Featured Image throws Error
`Something went wrong while saving this post. Warning: getimagesize(/var/www/web/pub/media/logo_site_1.png): failed to open stream: No such file or directory in /var/www/web/vendor/magento/module-media-gallery-synchronization/Model/CreateAssetFromFile.php on line 78`

After inspecting the files on server i see that the image DID saved in pub/media/magefan_blog/logo_site_1.png but as you can see from the error it tries to read the image from pub/media/logo_site_1.png

and bellow it also shows:

```
Warning: basename() expects parameter 1 to be string, array given in /var/www/web/vendor/magefan/module-blog/Block/Adminhtml/Post/Helper/Form/Gallery.php on line 103
Exception in /var/www/web/vendor/magento/framework/App/ErrorHandler.php:61
```

**Comment by Sil-B** [comment]
Same issue in 2.3.5-p2 and 2.9.6.1

**Comment by ihorvansach** [comment]
@karpa , @Sil-B , we are not able to reproduse this issue on clean Magento installation.  Please make sure that no other custom extension on your instance breaks the Magefan_Blog module.

If e.g. you have installed Amasty_Shopby (Amasty Layered Navigation), there is a known issue in this module, so please update Amasty_Shopby to v2.14.7 (more information here https://magefan.com/blog-featured-images-are-broken-after-uploading-in-magento-2 ).

Let me know if this helps.
