### ISSUE TITLE
Adding custom meta fields

### ISSUE THREAD

**Issue by Catlon** [magefan/module-blog#34]
Hello,

I would like to be able to add some **custom meta fields** in order to display information outside the actuel post content block.

For example, I would like to add a simple text field to handle excerpts that I would display in the category archive instead of the automated "first x characters in the post".

Thank you,

Cyril

**Comment by magefan** [comment]
@Catlon in 3-4 weeks, there will be a big update of blog extension (new v2.3.0). It will include this feature.

**Comment by Catlon** [comment]
Excellent!
That will be a very welcomed feature!
