### ISSUE TITLE
404 on all blog's pages - blog 2.9.7 with blog-graph-ql 2.1.0 and ScandiPwa 3.1

### ISSUE THREAD

**Issue by romeof1980** [magefan/module-blog#343]
/** prerequisites */
magefan/module-blog 2.9.7 installed via composer (url: https://github.com/magefan/module-blog.git)
magefan/module-blog-graph-ql 2.1.0 installed via composer (url: https://github.com/magefan/module-blog-graph-ql.git)
magefan/module-community 2.0.14 installed via composer (url: https://github.com/magefan/module-community.git)
magento 2.3.5
scandipwa/source: 3.1.6
`magento setup:upgrade && magento setup:di:compile && magento c:f`
from backend activating module-blog and setting route to "blog" (no slashes)
making sure categories and posts are present

go to homepage https://mysite.com/blog
same for category url or single post url i.e. https://mysite.com/blog/hello-world

/** expected results */
see the blog page (list of most recent posts)

/** actual results */
always getting 404

/** troubleshooting */
Have I read docs and FAQ? yes
Have I restarted services and VPS? yes
Have I double checked route and permalinks? yes
Flushed cache? yes
Can I add a widget with recent articles in home page? yes but when clicking on "Read more" still gives 404
Does `query GetPosts` works via GraphQl (using GraphQl PLayground)? yes, post_url is displayed but when visiting always 404
Does the blog_sitemap.xml get generated and show the expected urls? yes

thanks,
romeo

**Comment by ihorvansach** [comment]
@romeof1980 , thank you for your request.

Magento has graphQL url resolver https://devdocs.magento.com/guides/v2.4/graphql/queries/url-resolver.html
We extend url resolver, you can see this here
https://github.com/magefan/module-blog-graph-ql/blob/master/etc/schema.graphqls
`enum UrlRewriteEntityTypeEnum {
    MF_BLOG_INDEX
    MF_BLOG_POST
    MF_BLOG_CATEGORY
    MF_BLOG_TAG
    MF_BLOG_AUTHOR
    MF_BLOG_COMMENT
    MF_BLOG_ARCHIVE
    MF_BLOG_SEARCH
}`

and here

https://github.com/magefan/module-blog-graph-ql/blob/master/Plugin/Magento/UrlRewriteGraphQl/Model/Resolver/EntityUrl.php

So first you need to make request to URL resolver to get the information about the page 
 {
  urlResolver(url: "blog/hello-world") {
    id
    type
  }
}

Then having this information you are able to load proper blog data.  It should work similar to the load products 
a) get information about the page from the url resolver
b) using page type and id - load proper content

**Comment by romeof1980** [comment]
thanks @ihorvansach for your response.
Let me see if I got it correctly:
I understand that magefan-module-blog-graphql extends magento url resolver (see for example vendor/magefan/module-blog-graph-ql/etc/graphql/di.xml or src/vendor/magefan/module-blog-graph-ql/etc/di.xml or the various classes in src/vendor/magefan/module-blog-graph-ql/Model/ ). 

What I thought is that installing magefan-module-blog-graphql would be enough to have magefan-module-blog working properly with the pwa theme (thus leveraging Magento own graphQL url resolver as you pointed out https://devdocs.magento.com/guides/v2.4/graphql/queries/url-resolver.html ).

Are you suggesting that installing magefan-module-blog-graphql is not enough to make it work with pwa theme but I shoud instead further implement it? 

Perhaps a silly question but I haven't worked with your blog before in magento 2 pwa.
What I think is that installing magefan-module-blog-graphql should be enough and there is instead a bug either on it or on the ScandiPwa theme that I couldn't track down.

thanks a lot and have a great day,
romeo

**Comment by ihorvansach** [comment]
@romeof1980 , just installing magefan-module-blog-graphql is not enough to run blog on PWA. This module enable graphQL endpoints for blog so you can build PWA blog fronted.

Right now we are working on PWA add-ons for the PWA that will allow to easily launch PWA blog on Magento 2.

**Comment by romeof1980** [comment]
ok! understood. thanks a lot @ihorvansach for clarifying it
