### ISSUE TITLE
Custom url structure without path label

### ISSUE THREAD

**Issue by Catlon** [magefan/module-blog#35]
Hi,

i'm trying to **display category names in the post URL structure**, **without displaying the path label**.

Here is the standard URL structure for a category archive:
`http://domain.extension/blog/category/category-slug/post-name`

Here is what I would like:
`http://domain.extension/blog/category-slug/post-name`

Any help would be great.

Thanks,
C.

**Comment by magefan** [comment]
You cannot use category url key as part of post url. But using Permalink Settings in blog configurations you can set
http://domain.extension/blog/category-name/ - as category url
and
http://domain.extension/blog/post-name/  - as post url
