### ISSUE TITLE
Error 404! when trying to save post

### ISSUE THREAD

**Issue by Nayem323** [magefan/module-blog#352]
I am facing a very weird problem. When I am trying to save post that contains the word **"from"** in it's content redirecting me to error 404 page. 
Module version 2.9.7
Magento version 2.3.3

![image](https://user-images.githubusercontent.com/23062737/103141065-4e661700-4719-11eb-8543-8a7610b617e2.png)

**Comment by magefan** [comment]
@Nayem323 , sorry for the late reply on this. Most likely you have some security software on the server that blocks the request. We recommend contacting your hosting company or server admin regarding this issue.

**Comment by magefan** [comment]
Maybe related issue https://github.com/magefan/module-blog/issues/368
