### ISSUE TITLE
Bad CLS

### ISSUE THREAD

**Issue by ldopierala** [magefan/module-blog#358]
Hello,

Post page have a very bad / poor CLS. 
https://web.dev/cls/

Some modification are easy like :  Always include size attributes on your images and video elements.

Regards

Ludo

**Comment by magefan** [comment]
Thank you for your report. Please fill in the fields marked with (*), they are required.
-->

### Preconditions (*)

1.
2.

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.
