### ISSUE TITLE
CRITICAL: Warning: mb_strpos(): Offset not contained in string

### ISSUE THREAD

**Issue by davidwindell** [magefan/module-blog#359]
Since https://github.com/magefan/module-blog/commit/6939122febf399bd8963ffd4539fd4426245dc43 we are now seeing an error and the blog homepage can't load:

```
CRITICAL: Warning: mb_strpos(): Offset not contained in string in /var/www/vendor/magefan/module-blog/Model/Post.php on line 549 
```

**Comment by magefan** [comment]
Hello @davidwindell , thank you for your report. Could you please try to use this fix https://github.com/magefan/module-blog/commit/763a7ecc8fde5ebeaed3d2ba24160c6e37092242 .

Let us know if it works well for you.

**Comment by davidwindell** [comment]
Works well, thanks!

**Comment by magefan** [comment]
@davidwindell , also we want to let you know that this fix is also available in composer package magefan/module-blog v2.9.7.2
