### ISSUE TITLE
Magento backend shows warning message even after updating the blog

### ISSUE THREAD

**Issue by ShyamSuchakATP** [magefan/module-blog#360]
HI,
I have updated my Magento 2 backend with 2.9.7 version of blog extension. but admin logs, below warning message, is displayed. 
Attention! Your Blog extension version is extremely outdated. It is strongly recommended to update it to the latest version 2.9.7

How can This be removed or how can I update Magento 2 to recognize that blog version is 2.9.7?

**Comment by magefan** [comment]
@ShyamSuchakATP , please check this article
https://magefan.com/blog/manage-magento-2-admin-notifications

Let  us know if it helps.

**Comment by ShyamSuchakATP** [comment]
Thanks,

This helps.

Regards,
Shyam

**Comment by rashmi-rdeshpande** [comment]
Thanks this helped. But can we disable the notification for the blog or remove the plugin if we are not using it?
