### ISSUE TITLE
404 error when adding certain content on the Blog Post

### ISSUE THREAD

**Issue by jucaeis** [magefan/module-blog#368]
Hello,

We have installed your [Magento 2 blog extension](https://magefan.com/magento2-blog-extension) and we find it fantastic. During our tests, we have encountered an issue though: whenever we add certain info to the post content, we get a 404 error when we save it in the Magento 2 admin panel.

We are running on Magento 2.3.4 and an example of this is:

overflow: hidden;

Just writing that on the Content window causes a 404 error. Do you happen to know how to fix it?

KR
Juan

**Comment by magefan** [comment]
Hello @jucaeis ,

Can you please attach some screenshots? Also, you can contact us directly via email support@magefan.com

**Comment by jucaeis** [comment]
Hello,

No need. I found the problem: mod_security from the Apache Web Server was blocking the Save request. A rule triggered whenever the string overflow:hidden was added. It considered it as dangerous or SPAM-like. We have disabled the rule and now it works.

Thanks!
Juan
