### ISSUE TITLE
Load CSS only when needed

### ISSUE THREAD

**Issue by jorgb90** [magefan/module-blog#376]
**Describe the bug**
Blog CSS loads on every page. I guess this is only needed for the blog pages? Problem I am having and I guess I will not be the only one is that when your using generic CSS classes like the ones for FontAwesome:

.fa, .fas {font-family:'FontAwesome';font-weight: 900;font-size: 48px;}

that will affect the whole website! Please fix this. And again better would be if it doesn't load for every page.

**Preconditions:**
 - Magento Version: 2.4.2
 - Module Version: 2.10.1
 - PHP Version 7.4

**To Reproduce**!
-

**Expected behavior**
-

**Actual behavior**
-

**Screenshots**
-

**Additional context**
-

**Comment by magefan** [comment]
Hello @jorgb90 ,

Thank you for your report. We include the blog CSS on all pages as you are able to use blog post widgets and display recent/feature posts on any page.

To fix the issue please apply this fix
https://github.com/magefan/module-blog/commit/9f71c523dd4a90523be59133a2095cfe208e65cc

If you would like to remove the blog css from other pages (exept the blog pages) you can overide the Magefan_Blog default.xml layout in your theme (https://devdocs.magento.com/guides/v2.4/frontend-dev-guide/layouts/layout-override.html) and remove the css including, then create blog_default.xml in your theme and add those css including there.

Let us know if this works for you.

**Comment by jorgb90** [comment]
Yes thanks.
