### ISSUE TITLE
how to call catrgory wise list page 

### ISSUE THREAD

**Issue by virani06** [magefan/module-blog#38]
i want to call all blog category wise in stand alone page i tried with below code.

<div>{{block type="Magefan\Blog\Block\Post\PostList" category_id="1" template="Magefan_Blog::post/list.phtml"}}</div>

got the eroor.

**Comment by magefan** [comment]
You cannot use Magefan\Blog\Block\Post\PostList in CMS content. It required some child blocks like blog.posts.list.item

Please check this: https://github.com/magefan/module-blog/blob/master/view/frontend/layout/blog_post_list.xml
