### ISSUE TITLE
How can I manage author of the post?

### ISSUE THREAD

**Issue by clion007** [magefan/module-blog#398]
**Describe the bug**
I can't find autor table to save the author infomation and there is only a column in the post table is author_id. In the backend post form, the author is select from dropdown, so where is the author come from if no where I can add the author infomation to the DB?
**Preconditions:**
 - Magento Version: [e.g. 2.4.2]
 - Module Version: [e.g. 2.9.8]
 - PHP Version [e.g. 7.4.0]

**To Reproduce**

**Expected behavior**

**Actual behavior**
A clear and concise description of what actually happened.

**Screenshots**

**Additional context**

**Comment by magefan** [comment]
@clion007 Thank you for your report. If you use Blog Base Extension, the author of the blog post is the admin user, meaning if you want to create a blog author in Blog Base, you just create a new admin user. Then, in Blog Extra, you have a separate section and table for blog author. Please find more details on this in the following article: https://magefan.com/magento-2-blog-extension/create-blog-author.

**Comment by clion007** [comment]
Ok, I got it. Thanks!
