### ISSUE TITLE
Duplicated suffix added on post listing with pagination.

### ISSUE THREAD

**Issue by MTheProgrammer** [magefan/module-blog#401]
**Describe the bug**
Duplicated suffix added on post listing with pagination when Design Theme custom Page Title Suffix is enabled.

**Preconditions:**
 - Magento Version: 2.4.2
 - Module Version: 2.10.1.1
 - PHP Version 7.4

**To Reproduce**
1. Add Page Title Suffix for the current theme (Content -> Design -> Configuration: Edit theme)
2. Go to any blog listing page
3. Add pagination > 1 to the url if you do not have enough number of posts e.g. ?page=2
4. Check page metatitle value

**Expected behavior**
Generated meta title -` Page suffix` is added behind custom suffix defined in the design thee (My Suffix in this example)
```html
<meta name="title" content="Custom Blog Meta Title | My Suffix - Page 7">
```

**Actual behavior**
Design suffix is added twice.
```html
<meta name="title" content="Custom Blog Meta Title | My Suffix - Page 7 | My Suffix">
```

**Screenshots**

**Additional context**
In the block `Magefan\Blog\Block\Post\PostList::_prepareLayout` there is a code which is adding suffix twice, before real suffix from Magento Theme Design is applied.
```php
        if ($page > 1) {
            $this->pageConfig->setRobots('NOINDEX,FOLLOW');

            $this->pageConfig->getTitle()->set(
                $this->pageConfig->getTitle()->get() . ' - ' . __('Page') . ' ' . $page
            );
        }
```

**Comment by MTheProgrammer** [comment]
Here is my suggested PR https://github.com/magefan/module-blog/pull/402

**Comment by magefan** [comment]
Merged.
