### ISSUE TITLE
Post Alternative Image

### ISSUE THREAD

**Issue by IbrahimS2** [magefan/module-blog#413]
What is the best course of action to implement post an alternative image into the post view.phtml?

**Comment by magefan** [comment]
@IbrahimS2 , could you please describe more about your task? maybe some screenshosts?

**Comment by IbrahimS2** [comment]
@magefan Basically, I am trying to have another image displayed on the posting page; so in theory, we should have two fields:
Featured Image and Image, Image attribute/field should be displayed at the posting page only; and the rest as it is.
