### ISSUE TITLE
EOL periods causing the module to fail on build

### ISSUE THREAD

**Issue by P3rk1ns** [magefan/module-blog#417]
**Describe the bug**
On `bin/magento setup:upgrade` the module fails to build

**Preconditions:**
 - Magento Version: 2.4.4
 - Module Version: 2.10.6
 - PHP Version 7.4.28

**To Reproduce**
1. Run `bin/magento setup:upgrade` with the module installed.

**Expected behavior**
The modules setup scripts run as expected and `bin/magento setup:upgrade` does not fail

**Actual behavior**
Setup scripts fail returning the error attached
`Type Error occurred when creating object: Magento\Framework\Communication\Config\Data, Argument 2 passed to Magento\Framework\Reflection\TypeProcessor::resolveFullyQualifiedClassName() must be of the type string, null given, called in /var/www/html/vendor/magento/framework/Reflection/TypeProcessor.php on line 550`

**Additional context**
Many of the PHPdocs in https://github.com/magefan/module-blog/blob/master/Api/ManagementInterface.php have periods at the end of the parameter and return types. This causes the following line in https://github.com/laminas/laminas-code/blob/4.5.x/src/Reflection/ParameterReflection.php#L106 to return false meaning the function returns null causing the error listed in actual behaviour. To resolve this we have patched the module to exclude these EOL periods.

**Comment by magefan** [comment]
@P3rk1ns , please try this fix https://github.com/magefan/module-blog/commit/83e7aff9d83e0769f8f33303c7a085655a3daf4a

**Comment by magefan** [comment]
@P3rk1ns , also there is another commit to fix some issues on php8, please try to use master branch code, the new version will be released soon.

**Comment by magefan** [comment]
New version 2.10.7 has been released.
