### ISSUE TITLE
Setup install fail combined with new html sitemap module

### ISSUE THREAD

**Issue by frank-bokdam** [magefan/module-blog#418]
**Describe the bug**
During integration test / with fresh database setup `setup:install` will fail when `magefan/module-html-sitemap` is installed as well. I suspect this is due to `magefan/module-html-sitemap` adding a column to blog tables. As the sitemap module is using db_schema and the blog module is using patches, this leads to an error. 

**Preconditions:**
 - Magento Version: [e.g. 2.4.3-p2]
 - Module Version: [e.g. 2.10.6]
 - PHP Version [e.g. 7.4.0]

**To Reproduce**
1. Install both `magefan/module-blog` and `magefan/module-html-sitemap`
2. run `bin/magento setup:install`
3. Setup fails due to constraint error

**Expected behavior**
setup succesful.

**Actual behavior**
Setup fails due to foreign key errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/46452308/163412244-a6c6505d-0e59-45a2-aa17-335c702e9063.png)

**Additional context**
I've tried adding `magefan/module-blog` to sequence in `magefan/module-html-sitemap`, which did not seem to help. I suspect db_schema being ran before setup scripts.

**Comment by bohdan-berezhniy** [comment]
@frank-bokdam issue should be fixed.
Please upgrade to the latest versions:

- magefan/module-community
- magefan/module-html-sitemap
- magefan/module-blog
