### ISSUE TITLE
Type Error given on setup:upgrade, from Magento_Amqp

### ISSUE THREAD

**Issue by rjm87** [magefan/module-blog#420]
**Describe the bug**
When using module version 2.10.6 and latest Magento version 2.4.4, I get a error when performing setup:upgrade:

`Module 'Magento_Amqp':
Type Error occurred when creating object: Magento\Framework\Communication\Config\Data, Argument 2 passed to Magento\Framework\Reflection\TypeProcessor::resolveFullyQualifiedClassName() must be of the type string, null given, called in /data/web/magento2/vendor/magento/framework/Reflection/TypeProcessor.php on line 550`

**Preconditions:**
 - Magento Version: 2.4.4
 - Module Version: 2.10.6
 - PHP Version: 7.4.0

**To Reproduce**
1. Install Magento 2.4.4.
2. Install magefan/module-blog:2.10.6
3. Perform setup:upgrade

**Expected behavior**
All upgrades performed

**Actual behavior**
Error given as described.

**Comment by magefan** [comment]
@rjm87 please try this fix https://github.com/magefan/module-blog/commit/83e7aff9d83e0769f8f33303c7a085655a3daf4a

**Comment by magefan** [comment]
@rjm87  , also there is another commit to fix some issues on php8, please try to use master branch code, the new version will be released soon.

**Comment by magefan** [comment]
New version 2.10.7 has been released.
