### ISSUE TITLE
Scheduled Post not visible until manual FPC Cleanup with Varnish

### ISSUE THREAD

**Issue by ignatios96** [magefan/module-blog#433]
**ISSUE**
When we write a blog post and we set a future date to be published. When the date has been reached we need to manual cache flush the FPC in order to see the blog post.

**Preconditions:**
 - Magento Version: [2.4.3-p1]
 - Module Version: [2.10.4]
 - PHP Version [7.4.0]

**To Reproduce**
1. Add a new blog post with future date
2. Wait for the date to come
5. The post won't be visible in category list

**Expected behavior**
The post should be visible when the date has been reached.

**Comment by magefan** [comment]
Hello @ignatios96 , thank you for your report.

We've created a fix. You can find it here https://github.com/magefan/module-blog/pull/436/files .
It will be included in the next release of [Magento 2 Blog Extension](https://magefan.com/magento2-blog-extension)

**Comment by ignatios96** [comment]
Thanks for the update. I wll try out the fix and let you know for the results.
