### ISSUE TITLE
Previous and Next Post renders wrong articles

### ISSUE THREAD

**Issue by avstaylime** [magefan/module-blog#454]
There's a bug in `magefan/module-blog/Block/Post/View/NextPrev.php`

```
$collection = $this->_getFrontendCollection()
                        ->addFieldToFilter(
                            'publish_time',
                            ['lt' => $this->getPost()->getPublishTime()])
```

`->setOrder('publish_time', 'DESC');` is missing which results in prev/next being sorted incorrectly.

**Preconditions:**
 - Magento Version: 2.4.2
 - Module Version: 2.10.11
 - PHP Version: 7.4

**Comment by magefan** [comment]
Hello @avstaylime ,

Thank you for your report. Could you please try this fix https://github.com/magefan/module-blog/commit/a4cee81a867984c735cb7bec2fa537da22cd7a56 ? Let me know if it works well for you.

**Comment by avstaylime** [comment]
@magefan Yes, that's fine. Thanks.

Would you be able to release an update any time soon?

**Comment by magefan** [comment]
@avstaylime , there is a new patch version 2.10.11.1, you can get it via the composer.
