### ISSUE TITLE
SWAT Report Recommendation

### ISSUE THREAD

**Issue by nadpier** [magefan/module-blog#465]
**Describe the bug**
When we run a Site-Wide Analysis Tool (SWAT) report on the admin, one of the recommendations is to add a primary key to the MySQL table magefan_blog_product_tmp

**Preconditions:**
 - Magento Version: 2.4.5-p1
 - Module Version: 2.10.11.1
 - PHP Version 8.1

**To Reproduce**
1. Go to Magento Admin
2. Go to Reports > System Insights > Site-Wide Analysis Tool
3. Go to the Recommendations tab

**Comment by magefan** [comment]
We've checked the code and this table does not require the primary key. Instead, now we are adding index key for the product_id and store_id fields in this table.  This change will be available in the next extension release.
