### ISSUE TITLE
Can not upgrade to Blog ver2.3.x in Magento2.0.10

### ISSUE THREAD

**Issue by uflins** [magefan/module-blog#47]
When I upgrade the Blog Ext in Magento2.0.10. IIt Shows the class 
```
Magento/Catalog/Controller/Adminhtml/Category/Image/Upload.php
not found in 
Magfan/Blog/Controller/Adminhtml/Category/Image/Upload.php on line 17.
```

Should I just remove this [Magfan/Blog/Controller/Adminhtml/Category/Image/] folder for setup:upgrade?

**Comment by magefan** [comment]
Hello @uflins,

You cannot use blog version 2.3.x on Magento 2.0.x. Blog extension since v2.3.0 compatible only with v2.1.x.

Last available version for M2.0.x is 2.2.4 (https://github.com/magefan/module-blog/releases/tag/2.2.4)

**Comment by uflins** [comment]
Thank you~!
