### ISSUE TITLE
Getting Foreign Key Error

### ISSUE THREAD

**Issue by vrajeshpatel4u** [magefan/module-blog#471]
**Describe the bug**
After downloading this extension, ran setup upgrade command and getting foreign key error. 

**Preconditions:**
 - Magento Version: 2.4.5-p1
 - Module Version: 2.10.11
 - PHP Version 8.1.14

**To Reproduce**
1. Download Extension
2. Copy and Paste in app/code folder
3. Run magento setup upgrade command

**Expected behavior**
Setup upgrade command should work without error. 

**Actual behavior**
Getting Foreign Key Error. 

**Screenshots**
Attached SS : 
![MageFanError-](https://user-images.githubusercontent.com/40518060/222429383-7dde1558-7e3e-43ee-9393-9bfc83c65ddf.png)

**Comment by magefan** [comment]
@vrajeshpatel4u , thank you for your report. Could you please let us know if you just install the extension the first time or you tries to update it to the latest version?

**Comment by vrajeshpatel4u** [comment]
I am trying to install first time.

**Comment by magefan** [comment]
@vrajeshpatel4u , please try nex

1. Backup your database
2. Then follow "Remove Extension Data & Configuration" from this article 
3. Run bin/magento setup:upgrade

**Comment by vrajeshpatel4u** [comment]
Hello, 

I have tried but also getting same error while running setup:upgrade command. 

Thank you.

**Comment by remklov** [comment]
Is there any update on this? I got the same error. 
On my local DDEV environment everything worked fine, but on the hosted staging environment i get this error.

**Comment by magefan** [comment]
@vrajeshpatel4u , could you please contact our support team regarding this issue https://magefan.com/contact please also mention the link to this github issue.
