### ISSUE TITLE
Deprecated Functionality: Creation of dynamic property Magefan\Blog\Model\Config::$scopeConfig is deprecated in /var/www/html/magento/app/code/Magefan/Blog/Model/Config.php on line 118

### ISSUE THREAD

**Issue by Daniel-Zadora** [magefan/module-blog#483]
PHP error.

 - Magento Version: [2.4.6]
 - Module Version: [2.10.12]
 - PHP Version [8.2.4]

**To Reproduce**
1. Install
3. Enable extension in admin panel
3. Go to [url]/blog
 
<pre>1 exception(s):
Exception #0 (Exception): Deprecated Functionality: Creation of dynamic property Magefan\Blog\Model\Config::$scopeConfig is deprecated in /var/www/html/magento/app/code/Magefan/Blog/Model/Config.php on line 118
</pre>
<pre>
Exception #0 (Exception): Deprecated Functionality: Creation of dynamic property Magefan\Blog\Model\Config::$scopeConfig is deprecated in /var/www/html/magento/app/code/Magefan/Blog/Model/Config.php on line 118
#1 Magefan\Blog\Model\Config->__construct() called at [vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:121]
#2 Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject() called at [vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:66]
#3 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() called at [vendor/magento/framework/ObjectManager/ObjectManager.php:70]
#4 Magento\Framework\ObjectManager\ObjectManager->get() called at [vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:170]
#5 Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument() called at [vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:276]
#6 Magento\Framework\ObjectManager\Factory\AbstractFactory->getResolvedArgument() called at [vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:239]
#7 Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime() called at [vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:34]
#8 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments() called at [vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:59]
#9 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() called at [vendor/magento/framework/ObjectManager/ObjectManager.php:70]
#10 Magento\Framework\ObjectManager\ObjectManager->get() called at [vendor/magento/framework/Event/ObserverFactory.php:36]
#11 Magento\Framework\Event\ObserverFactory->get() called at [vendor/magento/framework/Event/Invoker/InvokerDefault.php:72]
#12 Magento\Framework\Event\Invoker\InvokerDefault->dispatch() called at [vendor/magento/framework/Event/Manager.php:65]
#13 Magento\Framework\Event\Manager->dispatch() called at [generated/code/Magento/Framework/Event/Manager/Proxy.php:95]
#14 Magento\Framework\Event\Manager\Proxy->dispatch() called at [vendor/magento/framework/View/Layout/Builder.php:79]
#15 Magento\Framework\View\Layout\Builder->loadLayoutUpdates() called at [vendor/magento/framework/View/Layout/Builder.php:63]
#16 Magento\Framework\View\Layout\Builder->build() called at [vendor/magento/framework/View/Page/Config.php:227]
#17 Magento\Framework\View\Page\Config->build() called at [vendor/magento/framework/View/Page/Config.php:240]
#18 Magento\Framework\View\Page\Config->publicBuild() called at [generated/code/Magento/Framework/View/Page/Config/Interceptor.php:32]
#19 Magento\Framework\View\Page\Config\Interceptor->publicBuild() called at [vendor/magento/framework/View/Result/Page.php:244]
#20 Magento\Framework\View\Result\Page->render() called at [vendor/magento/framework/View/Result/Layout.php:171]
#21 Magento\Framework\View\Result\Layout->renderResult() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#22 Magento\Framework\View\Result\Page\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#23 Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#24 Magento\Framework\View\Result\Page\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/View/Result/Page/Interceptor.php:95]
#25 Magento\Framework\View\Result\Page\Interceptor->renderResult() called at [vendor/magento/framework/App/Http.php:120]
#26 Magento\Framework\App\Http->launch() called at [generated/code/Magento/Framework/App/Http/Interceptor.php:23]
#27 Magento\Framework\App\Http\Interceptor->launch() called at [vendor/magento/framework/App/Bootstrap.php:264]
#28 Magento\Framework\App\Bootstrap->run() called at [pub/index.php:30]
</pre>

**Comment by magefan** [comment]
@Daniel-Zadora , to fix this issue, please update the Magefan_Blog module to the latest version [2.10.13](https://github.com/magefan/module-blog/releases/tag/2.10.13)
