### ISSUE TITLE
Unable to save Blog post, getting error 

### ISSUE THREAD

**Issue by rajesh-xcube** [magefan/module-blog#488]
While saving blog post getting below error. I have tried 2.4.6 (PHP 8) with magefan/module-blog version : 2.10.13.1

In exception exception.log file

[2023-04-20T08:43:30.436153+00:00] main.CRITICAL: Error: Call to undefined method Magefan\Blog\Controller\Adminhtml\Post\Save\Interceptor::getFilterInput() in /var/www/html/app/code/Magefan/Blog/Controller/Adminhtml/Post/Save.php:185
Stack trace:
#0 /var/www/html/app/code/Magefan/Community/Controller/Adminhtml/Actions.php(231): Magefan\Blog\Controller\Adminhtml\Post\Save->filterParams()
#1 /var/www/html/generated/code/Magefan/Blog/Controller/Adminhtml/Post/Save/Interceptor.php(41): Magefan\Community\Controller\Adminhtml\Actions->_saveAction()
#2 /var/www/html/app/code/Magefan/Community/Controller/Adminhtml/Actions.php(108): Magefan\Blog\Controller\Adminhtml\Post\Save\Interceptor->_saveAction()

**Comment by bohdan-berezhniy** [comment]
Hello @rajesh-xcube 
Please make sure that you use magefan/module-community with version 2.1.13

**Comment by rajesh-xcube** [comment]
It is working fine, thank you
