### ISSUE TITLE
Class 'Plumrocket\Amp\Block\Page\Head\Og\AbstractOg' not found

### ISSUE THREAD

**Issue by davidverholen** [magefan/module-blog#49]
since you added support for the plumrocket module, the blog module cannot be compiled anymore since the plumrocket module is not installed

**Comment by magefan** [comment]
@davidverholen  thank you for your report. Please find fix in commit https://github.com/magefan/module-blog/commit/636cb4b62c7d5f13faba124b3f9b87478671c89d
