### ISSUE TITLE
Issue with category and blog article with same name

### ISSUE THREAD

**Issue by rosen4o** [magefan/module-blog#493]
**Describe the bug**

**Preconditions:**
 - Magento Version: 2.4.6
 - Module Version: 2.10.13.2
 - PHP Version 8.2

You should have activated url scheme with including .html
If you have blog article with url /blog/avene.html and magento category with name /avene then blog article is giving 404
If you try to open it like /blog/avene it's opening normally
But url scheme is with .html and all generated links in categories and etc are with included .html

**Comment by magefan** [comment]
@rosen4o Thank you for submitting an issue. Unfortunately, we can't reproduce the issue on clean Magento 2.4.6. Could you please reproduce the issue on our [Blog Demo](https://magefan.com/magento2-blog-extension#live-demo), and let us know?

**Comment by rosen4o** [comment]
Have try to reproduce it on your instance but can't
Will try to gather more info

**Comment by magefan** [comment]
This issue has been closed due to inactivity. Please open it again if needed.
