### ISSUE TITLE
Post Image not upload

### ISSUE THREAD

**Issue by niku0911** [magefan/module-blog#497]
**Describe the bug**
Post Image not upload

**Preconditions:**
 - Magento Version: 2.4.5-p2
 - Module Version: 2.10.13
 - PHP Version 8.1

**To Reproduce**
1. Create a Post
2. Upload or Browse Image error showing
![image](https://github.com/magefan/module-blog/assets/50168477/b238df7f-08a4-476c-9163-0f7500516890)
3. added an image from the select from gallery option
4.  save a post but image not saved properly
![image](https://github.com/magefan/module-blog/assets/50168477/a086ee1f-53be-4009-b729-215ede1f72f6)

**Expected behavior**
Need to upload the image
![image](https://github.com/magefan/module-blog/assets/50168477/cca96315-8d3e-4ad6-bbd6-bf1b264dcce8)

**Actual behavior**
![image](https://github.com/magefan/module-blog/assets/50168477/b238df7f-08a4-476c-9163-0f7500516890)

**Comment by niku0911** [comment]
Hi @magefan ,

Still the same issue, please check my video.
https://www.awesomescreenshot.com/video/17613858?key=1801964fbc7590ee55a42256d2139ac4

**Comment by magefan** [comment]
@niku0911 , could you please upload this image for example in catalog > category  > content >  category image

There may be an issue with the image itself.

Let us know the result.

**Comment by niku0911** [comment]
Working fine in category or other default pages
![image](https://github.com/magefan/module-blog/assets/50168477/ad539dd6-032a-400a-91bc-df80debaca06)

**Comment by magefan** [comment]
@niku0911 , could you please contact us via email support@magefan.com link this ticket, and attache the image file you use so we can try it on our testing environment?

**Comment by niku0911** [comment]
ok sure
