### ISSUE TITLE
Getting Fatal Error

### ISSUE THREAD

**Issue by Sam-PUMP** [magefan/module-blog#50]
I'm getting a fatal error when compiling: 
` Fatal error:  Class 'Plumrocket\Amp\Block\Page\Head\Ldjson\Cms' not found invendor/magefan/module-blog/Block/Amp/Ldjson/PostList.php on line 14`

Previous version was working for me but upgrade gives that error for some reason.

**Comment by Sam-PUMP** [comment]
Hi yes that fixes it. Except I have to do it manually because composer won't let me upgrade to 2.4.1 and keeps me at 2.4.0 do you know why? I can only use the composer version so is there a way to force it?

```
our requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package magefan/module-blog 2.4.1 exists as magefan/module-blog[2.0.2, 2.1.0, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.2.4, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.4.0, dev-master] but these are rejected by your constraint.
```

thanks!

**Comment by magefan** [comment]
@Sam-PUMP, it's require some time for packagist.org to update package. Now v2.4.1 is available for install using comoser. In future we will to try update package manually to make last version available for composer faster.
