### ISSUE TITLE
PHP Fatal error:  Class 'Magento\Catalog\Controller\Adminhtml\Category\Image\Upload' 

### ISSUE THREAD

**Issue by hdisplay** [magefan/module-blog#51]
PHP Fatal error:  Class 'Magento\Catalog\Controller\Adminhtml\Category\Image\Upload' not found in /var/www/html/magento/app/code/Magefan/Blog/Controller/Adminhtml/Upload/Image/Action.php on line 17

**Comment by hdisplay** [comment]
Magento 2.0.7

**Comment by magefan** [comment]
Duplicate issue https://github.com/magefan/module-blog/issues/47 
Please try to find solution in closed issues first before open new one.
