### ISSUE TITLE
Enable "Modern" on post view exposes CSS root location

### ISSUE THREAD

**Issue by FadedOut** [magefan/module-blog#513]
**Describe the bug**
I believe this could be a slight security issue. Not really major but not something I think should be happening (I know I don't want it showing on my website...there are of course people that scan the page sources for multiple reasons). While enabling the "Modern" setting for post view, you are able to see the full root path to the bootstrap-4.4.1-custom-min.css file and consequentially the whole website.

**Preconditions:**
 - Magento Version: 2.4.6-p1
 - Module Version: 2.10.14
 - PHP Version: 8.2

**To Reproduce**
1. Go to Configuration
2. Go to Post Page (Post View) > Design
3. Enable "Modern"
4. View frontend page source using browser dev-tools. View the list for the blog view, "_post-view post-view-modern". Two lines above it will show the exposed root location of file.

**Expected behavior**
Should not have this line at all. If it is kept, it should not expose full root directory of website.

**Actual behavior**
Shows the exposed root location of file.

**Screenshots**
![magento-magefan-blog-modern-blog-view-expose-css-root-location](https://github.com/magefan/module-blog/assets/12685113/5cd17a86-7187-4253-878f-57417077dc2c)

**Additional Information**
It does not show this while using the "Use System Settings" aka non-modern.

**Comment by magefan** [comment]
@FadedOut , thank you for your report. Could you please try to use this fix https://github.com/magefan/module-blog/commit/3ba9fb53b15fe8f86014baa78a8b7cc8cab42b5f .

I also be included in the next extension release.

**Comment by FadedOut** [comment]
@magefan 

Thank you for that quick fix 👍🙂. That did the trick!

![magento-magefan-blog-modern-blog-view-file-location-fixed](https://github.com/magefan/module-blog/assets/12685113/83b2ff38-cb08-4cfa-a4e0-6e9144710802)
