### ISSUE TITLE
Can not install

### ISSUE THREAD

**Issue by jonshkreli** [magefan/module-blog#52]
when i try to install it via files download, I followed instructions:
....
when i run the secon command i get this error:
Fatal error: Interface 'Magefan\Blog\Api\ManagementInterface' not found in C:\xampp\htdocs\mage1\app\code\Megafan\Blog\Api\CategoryMana
gementInterface.php on line 11

and if i run the third command and/or try to open admin pages i get this:
Exception #0 (ReflectionException): Class Magefan\Blog\Observer\PredispathAdminActionControllerObserver does not exist

and this in homepage:
Exception #0 (ReflectionException): Class Magefan\Blog\Observer\PageBlockHtmlTopmenuBethtmlBeforeObserver does not exist

PS: i checked many times and files all exist. and they have all permissions from all users.
I am using lastest magento version.

**Comment by magefan** [comment]
@jonshkreli, are you sure, you uploaded all files from archive? and have no issues with file permissions?
what magento and blog version do you use?

**Comment by jonshkreli** [comment]
Hey i tried to delete and try it again. This time i downloaded from "clone or download", not from the zip link provided in installing instructions.
And this time installing worked.

But when i try to go into categories pages i get this error:
2 exception(s):
Exception #0 (Zend_Db_Statement_Exception): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mage1.magefan_blog_category' doesn't exist, query was: SELECT COUNT(*) FROM `magefan_blog_category` AS `main_table`
Exception #1 (PDOException): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mage1.magefan_blog_category' doesn't exist



And this one when i try to go to page posts:

2 exception(s):
Exception #0 (Zend_Db_Statement_Exception): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mage1.magefan_blog_post' doesn't exist, query was: SELECT COUNT(*) FROM `magefan_blog_post` AS `main_table`
Exception #1 (PDOException): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mage1.magefan_blog_post' doesn't exist

Exception #0 (Zend_Db_Statement_Exception): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mage1.magefan_blog_post' doesn't exist, query was: SELECT COUNT(*) FROM `magefan_blog_post` AS `main_table`


 While import and configuration links works. I have to say that i flushed cache and the result is the same. I were able to save a meta keyword in configuration menu successfully.

**Comment by magefan** [comment]
@jonshkreli, it's look like install db data and schema where not runned. Are you sure, that you have runned
php bin/magento setup:upgrade command? I yes, please find setup_module table in DB, and remove record where module = Magefan_Blog, then run setup:upgrade command again.
