### ISSUE TITLE
Call to a member function getRelatedProducts()

### ISSUE THREAD

**Issue by webamondo** [magefan/module-blog#520]
Upgraded to the lastest version

Now getting this error 

 main.CRITICAL: Error: Call to a member function getRelatedProducts() on null in vendor/magefan/module-blog/Block/Sidebar/PostRelatedProducts.php:67

Magento ver. 2.4.6-p1

Blog Extension v2.11.0

**Comment by magefan** [comment]
@webamondo , thank you for your report. Could you please try this fix https://github.com/magefan/module-blog/commit/8764f871ea1090231c852c14bf3160bf14e78163 . Let us know if it works well for you.

**Comment by webamondo** [comment]
@magefan that has worked, thank you
