### ISSUE TITLE
Save category is not working

### ISSUE THREAD

**Issue by MLisiecki** [magefan/module-blog#527]
Error: Call to undefined method Magefan\Blog\Controller\Adminhtml\Category\Save\Interceptor::getFilterInput() in app/code/Magefan/Blog/Controller/Adminhtml/Category/Save.php:54

I have check - there is no any getFilterInput() function inside. 

Latest version 2.11.0.1

**Comment by MLisiecki** [comment]
I have downloaded from shop and this issue disapears. You can close it.

**Comment by magefan** [comment]
@MLisiecki , the problem was that you updated Magefan_Blog extension and keep the old version of Magefan_Community (https://github.com/magefan/module-community).
