### ISSUE TITLE
Urgent Help:How to show post listing on cms page

### ISSUE THREAD

**Issue by mahimohit** [magefan/module-blog#54]
Hello,

I want to show post category wise on cms page. Can its possible.

**Comment by magefan** [comment]
You can display recent posts by category using widget.

**Comment by mahimohit** [comment]
No, I want to show a post accordingly category on separate page just like
category 1 menu shows only category 1 post and so on.

On 29-Dec-2016 11:24 AM, "Magefan" <notifications@github.com> wrote:

You can display recent posts by category using widget.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/magefan/module-blog/issues/54#issuecomment-269585338>,
or mute the thread

**Comment by magefan** [comment]
@mahimohit, by using recent posts widget you can indicate specific category from with you want to display posts.
