### ISSUE TITLE
When trying to create a category through the admin panel

### ISSUE THREAD

**Issue by mauricio-tonny** [magefan/module-blog#540]
**Describe the bug**

When trying to create a category through the admin panel it returns the following error:

Call to undefined method Magefan\Blog\Controller\Adminhtml\Category\Save\Interceptor::getFilterInput() in /var/www/html/app/code/Magefan/Blog/Controller/Adminhtml/ Category/Save.php:54

**Preconditions:**
 - Magento Version: [e.g. 2.4.6-p3]
 - Module Version: [e.g. 2.11.0.1 and 2.10.12.3]
 - PHP Version [e.g. 8.1]

**To Reproduce**
When trying to create a category through the admin panel

**Expected behavior**

**Actual behavior**
A clear and concise description of what actually happened.

**Screenshots**

**Additional context**

**Comment by magefan** [comment]
@mauricio-tonny , to fix this issue, please make sure that you have the latest version of magefan/module-community package (Magefan_Community module). You can find it here https://github.com/magefan/module-community

Let us know if it helps.
