### ISSUE TITLE
main.CRITICAL: Error: Call to a member function getItemById() on array in /vendor/magefan/module-blog/Model/UrlResolver.php:190

### ISSUE THREAD

**Issue by Top-CMS** [magefan/module-blog#578]
Hello,

After updating Magento to 2.4.7 and magefan/module-blog 2.11.3 I get this error:
main.CRITICAL: Error: Call to a member function getItemById() on array in /vendor/magefan/module-blog/Model/UrlResolver.php:190

That is a link to a blogpost with category in url. Enabled under Permalink Settings - Use Categories Path for Post URLs - Yes
and Category Route: Category 

Before update it works, after update both (Magento 246 to 247 and blog 2.11.x to 2.11.3), I got these errors.

When I set  Use Categories Path for Post URLs to No, urls working fine, but then I miss the categories in url and lose some rankings.

What is the problem?

**Comment by magefan** [comment]
Thank you for your report. To fix this issue, please use this fix https://github.com/magefan/module-blog/commit/195e9261cbc4eaf6efc1bbd26a07950992636573 or update the extension to the newer version  2.11.3.1 (https://github.com/magefan/module-blog/releases/tag/2.11.3.1)
