### ISSUE TITLE
Blog route change not reflected in main menu

### ISSUE THREAD

**Issue by mgomma** [magefan/module-blog#58]
I did change the blog route from admin settings but still the menu item refer to **blog**

**Comment by magefan** [comment]
@mgomma we have checked on the latest v2.4.3 and cannot detect such issue. Maybe you forgot to clean magento cache or this link is static in your theme. If my suggestions are wrong, please update blog extension to the newest version.

**Comment by mgomma** [comment]
I did that update and it is not hardcoded in the theme.

When I try **/blog** or **/{my_cutoum_route}** both works fine.

But the menu item still has the url **/blog** instead of **{my_cutoum_route}** which I set.

**Comment by magefan** [comment]
@mgomma, please contact us via our [contact form](http://magefan.com/contact/)  and provide ssh and admin panel credentials so we can check.
