### ISSUE TITLE
Misunderstand save action

### ISSUE THREAD

**Issue by DUC-ANH-LY** [magefan/module-blog#589]
Hello magefan, I have question on how do you guys save post_category relationship, when i debug save action, i just saw Post to be saved , how magic underneath the hood

![image](https://github.com/magefan/module-blog/assets/92360920/e405c8bd-2450-4369-acb3-1ccffbaa37e5)

**Comment by DUC-ANH-LY** [comment]
hi any one have me

**Comment by magefan** [comment]
@DUC-ANH-LY , please pay attention to the resource model after save https://github.com/magefan/module-blog/blob/master/Model/ResourceModel/Post.php
