### ISSUE TITLE
Feature Request | Provide Tests

### ISSUE THREAD

**Issue by DavidLambauer** [magefan/module-blog#59]
Could you provide Tests for this Module?

**Comment by magefan** [comment]
Hello @DavidLambauer we could include this in next release. What exactly type of tests do you need first of all? 

Little off-top:
You can always check blog extension on our demo: http://blog-demo.magefan.com/blog

**Comment by DavidLambauer** [comment]
Hii! 

I would appreciate if the API Implementation would be tested. If so, I would add the Module to the [Magento 2 Awesome List](https://github.com/DavidLambauer/awesome-magento2).

**Comment by magefan** [comment]
Feature added to backlog.
