### ISSUE TITLE
how can i know what starter point or flow of  layout 

### ISSUE THREAD

**Issue by DUC-ANH-LY** [magefan/module-blog#591]
hello team, I'm confused about how layout works, first i remove `<update handle="blog_post_list"/>` then it still display blog
![image](https://github.com/magefan/module-blog/assets/92360920/54514aa8-5a86-4af5-b0e9-726bbfd85e34)
![image](https://github.com/magefan/module-blog/assets/92360920/780f1f70-bfbd-4a73-b23f-9896f668c3a4)

when i go to Magefan\Blog\Block\Index that contains lots of layer such as PostList,AbstractList,Template . I dont know what is start point to display this `blog.posts.list` part.

**Comment by magefan** [comment]
@DUC-ANH-LY , why you commented this line?
Without it it will not work properly

**Comment by DUC-ANH-LY** [comment]
no i just want to understand work flow

**Comment by magefan** [comment]
@DUC-ANH-LY , please read the code and layout XML. You can learn more about how Magento Front works here https://developer.adobe.com/commerce/frontend-core/guide/
