### ISSUE TITLE
Issue during categories import in the WordPress import

### ISSUE THREAD

**Issue by MaximeChamont** [magefan/module-blog#593]
**Describe the bug**
After an import of WordPress DB, I encounter this issue during the import of the categories:

```
Exception message: Unique constraint violation found                                                                  
Trace: <pre>#1 Magefan\Blog\Model\ResourceModel\Category\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]              
#2 Magefan\Blog\Model\ResourceModel\Category\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]  
#3 Magefan\Blog\Model\ResourceModel\Category\Interceptor->___callPlugins() called at [generated/code/Magefan/Blog/Model/ResourceModel/Category/Interceptor.php:86]                          
#4 Magefan\Blog\Model\ResourceModel\Category\Interceptor->save() called at [vendor/magento/framework/Model/AbstractModel.php:663]                                 
#5 Magento\Framework\Model\AbstractModel->save() called at [generated/code/Magefan/Blog/Model/Category/Interceptor.php:419]                                                         
#6 Magefan\Blog\Model\Category\Interceptor->save() called at [vendor/magefan/module-blog/Model/Import/Wordpress.php:100]
[...]
```

**Preconditions:**
 - Magento Version: 2.4.7
 - Module Version: 2.11.4
 - PHP Version: 8.2.18

**To Reproduce**
1. Go to 'Magefan > Import > Import from WordPress'
2. Click on 'Start Import'
3. The error "Unique constraint violation found

**Additional context**
This error is due to your method lookupStoreIds() (of your Magefan\Blog\Model\ResourceModel\Category class) used in the _afterSave() method which not reload the data after the first save of all categories so it tries to reimport the same data in the next save.

**Comment by magefan** [comment]
@MaximeChamont , could you please try to use this fix https://github.com/magefan/module-blog/pull/596/files

Let us know if it works for you.

**Comment by magefan** [comment]
new version released

**Comment by MaximeChamont** [comment]
It works without error now. Thank you.
