### ISSUE TITLE
Syntax error in the file view/frontend/templates/lazyload-js.phtml

### ISSUE THREAD

**Issue by MaximeChamont** [magefan/module-blog#594]
**Describe the bug**
```
SyntaxError: Unexpected token '}'
```
coming from your last rework of the file https://github.com/magefan/module-blog/commit/c5c322e687d4757031c7a80a5c7cade3e6d93313#diff-47fdd2b43655ce435d81e63fb812096f0b7073e6547ea3d55dc64708a2c6df2f

**Preconditions:**
 - Magento Version: 2.4.7
 - Module Version: 2.11.5
 - PHP Version: 8.2

**To Reproduce**
1. Go to the blog homepage
2. Open the browser console
3. See the error

**Comment by magefan** [comment]
@MaximeChamont , thank you for your report. Please use this fix https://github.com/magefan/module-blog/commit/64d350c3a84d1cd187756e441ce1566ae58af6bf 
Once allied don't forget to redeploy static content. Please let us know if this works for you.

**Comment by MaximeChamont** [comment]
Thanks for your return but your fix is incorrect.
It is not an issue with a missing semicolon but it is due to an additional bracket here: https://github.com/magefan/module-blog/commit/c5c322e687d4757031c7a80a5c7cade3e6d93313#diff-47fdd2b43655ce435d81e63fb812096f0b7073e6547ea3d55dc64708a2c6df2fR52

**Comment by magefan** [comment]
@MaximeChamont , yes, you completely right, here is the change https://github.com/magefan/module-blog/commit/ef5e8d06c5647582ba4edfb11aecffa539b729d5

**Comment by MaximeChamont** [comment]
It works fine now, thanks !
