### ISSUE TITLE
Product key is required if Hyva Theme is installed

### ISSUE THREAD

**Issue by antoniocarboni** [magefan/module-blog#597]
If the Hyva Theme is installed in the Magento instance, the module deactivates itself, resulting in all the blog pages returning 404 errors. This has caused significant SEO issues for one of our stores.

In my opinion, this is a bad practice. The module is free and should work independently of other installed modules.

We could have developed a custom compatibility module, or we could use Hyva on another website where the blog isn't used.

It's acceptable to sell a compatibility module, but using these tactics to try to sell more licenses is not the right approach imho.

**Comment by magefan** [comment]
@antoniocarboni , starting from Magefan [Blog v2.11.4](https://magefan.com/magento2-blog-extension/change-log) Hyva theme compatibility is available only in the [Plus and Extra](https://magefan.com/magento2-blog-extension/pricing#:~:text=hyva) plans. Using Magefan_Blog >= v2.11.4 module with any of Hyva_MagefanBlog* modules now requires a product key.

Public repositories for the Hyva Theme Packages have been abandoned.
[magefan/hyva-theme-blog](https://github.com/magefan/hyva-theme-blog)
[magefan/hyva-theme-blog-plus](https://github.com/magefan/hyva-theme-blog-plus)
[magefan/hyva-theme-blog-extra](https://github.com/magefan/hyva-theme-blog-extra)
[magefan/hyva-theme-blog-author](https://github.com/magefan/hyva-theme-blog-author)

The latest versions of magefan/hyva-theme-blog* packages are available in our private repository for Plus and Extra blog users.
https://magefan.com/downloadable/customer/products?hyva=1 

To continue using Magefan_Blog with Hyva_MagefanBlog* you need to downgrade to Blog v2.11.3 or upgrade to[ Plus or Extra blog editions](https://magefan.com/magento2-blog-extension/pricing) ([how to upgrade](https://magefan.com/magento2-blog-extension/upgrade-plan)).

**Comment by antoniocarboni** [comment]
Sure
My point is about 'forcing' the user to buy the license (perhaps the user has a custom frontend based on Hyvä or is using it on another website that shares the module). As a result, the user is forced to give up updates (potentially even important security ones) just because they haven't purchased a license that may not be necessary.
