### ISSUE TITLE
Cannot set custom categories on sidebar

### ISSUE THREAD

**Issue by JacobDrummond** [magefan/module-blog#60]
### Environment
1. Apache 2.4.17
2. MySQL  5.0.11-dev
3. PHP 5.6.15
4. Magento 2.1.3
5. Magefan_Blog 2.4.3

### Steps to reproduce
1. Call Magefan\Blog\Block\Sidebar\Categories->setGroupedChilds($customCategoryTree)
2. Call Magefan\Blog\Block\Sidebar\Categories->getGroupedChilds()

### Expected result
1. $customCategoryTree should be returned

### Actual result
1. Magefan_Blog's normal category tree is returned

### Solution
1. [This line](/magefan/module-blog/blob/2.4.3/Block/Sidebar/Categories.php#L52) should be changed to `if (!$this->hasData($k)) {`

**Comment by magefan** [comment]
Thank you @JacobDrummond , we have made change (https://github.com/magefan/module-blog/commit/07753028767a657ac71a4c5b8dec96545fddb207) It will be included in next release.
