### ISSUE TITLE
Cannot remove all values from the 'Co-Authors' field.

### ISSUE THREAD

**Issue by lukoc** [magefan/module-blog#604]
**Describe the bug**
You cannot remove all values from the 'Co-Authors' field on [Magento 2 Blog](https://magefan.com/magento2-blog-extension) Post edit page.

**To Reproduce**
1. Go to https://magefan.com/magento2-blog-extension#live-demo  Admin Panel Demo
2. Edit any post where Co-Authors field is filled
3. Clear all coauthors from this post and save post

**Expected behavior**
All values from the Co-Authors field are removed after post save.

**Actual behavior**
At least one value in the Co-Authors field remains selected after post save.

**Comment by magefan** [comment]
@lukoc , could you please try this fix https://github.com/magefan/module-blog/commit/ecb99103b5e39d4d7fa3c67025f8d25986236ea2 , let us know if it helps

**Comment by lukoc** [comment]
@magefan Yes, this change solves the problem, thank you
