### ISSUE TITLE
Class 'PostListTemplate' not available.

### ISSUE THREAD

**Issue by hiten-gautami** [magefan/module-blog#606]
Magefan\Blog\Model\Config\Source\PostListTemplate

**Comment by magefan** [comment]
@hiten-gautami , thank you for your report.
If you check https://github.com/magefan/module-blog/blob/master/etc/di.xml you will see that the Magefan\Blog\Model\Config\Source\PostListTemplate is a virtual type.

To make it available, please run the command
bin/magento setup:di:compile

Please let us know if it helps to solve the issue.
