### ISSUE TITLE
Post content is not saved when deleting content

### ISSUE THREAD

**Issue by accentinteractive** [magefan/module-blog#608]
**Describe the bug**

**Preconditions:**
 - Magento Version: 2.4.6-p6
 - Module Version: 2.10.14
 - PHP Version 8.2.22

**To Reproduce**
1. Open an existing blog post with multiple colums
2. Delete 50+ characters from a single column
3. Click the Save (or save and continue) button
4. See that the content you tried to delete didn't get deleted

**Screenshots**
[Video of the issue](https://github.com/user-attachments/assets/ccb7444b-8739-44ba-ad4c-24f2de849b81)

**Comment by magefan** [comment]
@accentinteractive , thank you for your report. 

Could you please insert the same content to the content > page (cms page) and see if you expect the same issue there? 

Please let us know the result.

**Comment by accentinteractive** [comment]
@magefan The problem doesn't seem to occur there.

**Comment by magefan** [comment]
Please contact our support team via email support@magefan.com regarding this issue.
