### ISSUE TITLE
Masonry template on Porto

### ISSUE THREAD

**Issue by bpaulette** [magefan/module-blog#61]
Hey!  Nice work on this extension!

I've installed this on a M2 Porto build, and the recent_masonry.phtml template doesn't seem to be working.  Posts are displaying in a single column.

Could this be a simple fix?

![blog-settings](https://cloud.githubusercontent.com/assets/25908154/23136222/547a18a0-f761-11e6-93d4-7e0aaba219d1.jpg)

![masonry-not-working](https://cloud.githubusercontent.com/assets/25908154/23136150/f44bdacc-f760-11e6-91f8-82ca4bd2910b.jpg)

**Comment by dankocrama980** [comment]
You can update the CSS to change it to a column layout

**Comment by bpaulette** [comment]
I'm sorry, not sure I understand.  

I don't actually want them all in a single column (that's what it's doing now).  I was expecting the widget to behave like on the demo site, where the recent posts are laid out like this

![blog-masonry](https://cloud.githubusercontent.com/assets/25908154/23136333/e65a3de0-f761-11e6-9c23-456b771cf37e.jpg)

**Comment by magefan** [comment]
@bpaulette first of all please check if porto theme does not override recent_masonry.phtml template, second one I think some css for .blog-widget-recent is missing in theme css (check this file: https://github.com/magefan/module-blog/blob/master/view/frontend/web/css/blog-m.css) .

Also be sure, that masonry js is loaded.
