### ISSUE TITLE
Issues with Blog Media Gallery In SmartWave Porto Theme

### ISSUE THREAD

**Issue by MagefanCustomer** [magefan/module-blog#614]

**Comment by magefan** [comment]
<p>If you have any issues with the media gallery in a blog post using SmartWave Porto Theme, please follow the steps below.</p>
<p>First of all, if there are no blog post media gallery settings in the Magento 2 admin panel, please make sure that you use the latest version of <a title="Change log for Magento 2 Blog Extension
" href="https://magefan.com/magento2-blog-extension/change-log">blog extension</a>.</p>
<p>Then create a new file in your theme directory:</p>
<pre>app/design/<strong>ThemeVendor</strong>/<strong>themename</strong>/Magefan_Blog/templates/post/view/gallery.phtml</pre>
<p>and add&nbsp;<a title="Blog Post Media Gallery Template for Porto Theme" href="https://raw.githubusercontent.com/magefan/module-blog/master/view/frontend/templates/post/view/gallery_porto_fanybox2.phtml" target="_blank" rel="nofollow noopener">this code</a> into it.</p>
<p>You need to do this as by default <a title="#1 Magento 2 blog extension" href="https://magefan.com/magento-2-extensions-blog-extension">Magefan Blog Extension</a> use FancyBox 3 for media gallery, and Porto theme uses FancyBox 2 and this new template will run media gallery using FancyBox 2.</p>
<p>If you need to change Fancybox settings please edit&nbsp;<strong>gallery.phtml</strong> file using <a title="FancyBox documentation" href="http://fancyapps.com/fancybox/" target="_blank" rel="nofollow noopener">FancyBox documentation</a>.</p>
