### ISSUE TITLE
Upgrade From Megnor Blog to Magefan Blog

### ISSUE THREAD

**Issue by MagefanCustomer** [magefan/module-blog#616]

**Comment by magefan** [comment]
<p><strong>Megnor Blog</strong> is a&nbsp;distribution of Magefan Blog. If you use&nbsp;<strong>Megnor </strong>Blog extension you might want to replace it with the latest version of Magefan <a title="Best Magento 2 Blog Extension" href="https://magefan.com/magento-2-extensions-blog-extension">Magento 2 blog extension</a>&nbsp;to get new features, security improvements, and bug&nbsp;fixes.&nbsp;The&nbsp;<a title="Magefan Blog Changelog" href="https://magefan.com/magento-2-extensions-blog-extension">changelog</a>&nbsp;can be found&nbsp;on&nbsp;our website.</p>
<p><strong>To replace Megnor_Blog with Magefan_Blog, please follow the steps below:</strong></p>
<p>1. Make a full backup of your Magento 2 files and Data Base.</p>
<p>2. Rename all Data Base tables that start with&nbsp;'<strong>megnor_blog_</strong>...' to&nbsp;'<strong>magefan_blog_...</strong>'. E.g. rename "megnor_blog_post" table to "megefan_blog_post". You can use PhpMyAdmin for this purpose.</p>
<p>3. Rename the folder</p>
<pre>app/design/frontend/ThemeVendor/theme_name/<strong>Megnor_Blog&nbsp;</strong></pre>
<p>to</p>
<pre>app/design/frontend/ThemeVendor/theme_name/<strong>Megefan_Blog&nbsp;</strong></pre>
<p>4. Remove the folder</p>
<pre>app/code/Megnor/Blog</pre>
<p>5. Install <a title="How to install Magefan Blog for Magento 2?" href="https://magefan.com/blog/magento2-blog-extension-installation">Magefan Blog Extension</a>.</p>
<p>6. Recreate blog widgets. For homepage widget use&nbsp;custom template "Megefan_Blog::widget/list_home.phtml" in widget settings.</p>
<p>&nbsp;</p>
<h3>Need help?</h3>
<p>Please <a title="Contact Magefan" href="https://magefan.com/contact">contact us</a> if you have any questions.</p>
