### ISSUE TITLE
How to Change The Layout For All Magento 2 Blog Pages?

### ISSUE THREAD

**Issue by MagefanCustomer** [magefan/module-blog#617]

**Comment by magefan** [comment]
<p>If you use <a title="Best Magento 2 Blog Extension" href="https://magefan.com/magento-2-extensions-blog-extension">Magefan Blog Extension for Magento 2</a>&nbsp;and need to change the layout e.g. from "2 columns&nbsp;with a right sidebar" to "2 columns&nbsp;with a left sidebar" for all blog pages, please do next:</p>
<p>1. Create a file</p>
<pre>app/design/ThemeVendor/themename/Magefan_Blog/layout/blog_default.xml</pre>
<p>2. Add the code into it</p>
<pre>&lt;?xml version="1.0"?&gt;<br>
&lt;page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" <strong>layout="2columns-left"</strong> xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd"&gt;<br>&lt;/page&gt;</pre>
<p>3. Save the file and flush Magento 2 caches.</p>
<p>&nbsp;</p>
<p>For the&nbsp;<strong>layout</strong> attribute you can use such values as:<br><span class="webkit-html-attribute-value">&nbsp;- 1column<br></span>&nbsp;- 2columns-left<br>&nbsp;- 2columns-right<br>&nbsp;- 3columns</p>
<p>&nbsp;</p>
