### ISSUE TITLE
Blog list text on breadcrumbs

### ISSUE THREAD

**Issue by jm111015** [magefan/module-blog#62]
Hi, 

I would like to ask how to update the blog text on breadcrumbs, I updated the Category Top Navigation but it seems nothing happened.

From **Home > Blog**
 I want it to be updated with this

**Home > News & Events**

Thank you.

**Comment by magefan** [comment]
@jm111015 you can try to use for this magento inline translation.

**Comment by magefan** [comment]
@jm111015  it is fixed by latest commit https://github.com/magefan/module-blog/commit/c9d6521e63852c3196268136d039d5c0a84cd4fb and will be included in next release.
