### ISSUE TITLE
REST API

### ISSUE THREAD

**Issue by msliman** [magefan/module-blog#63]
I'd like to ask how to call the REST APIs. Ex:
- GET news list (title, photo, brief, time)
- GET news details(title, body, photo)

**Comment by magefan** [comment]
1. Download the latest version from master branch (v2.4.3 is not included this feature)
2. Then look at this file https://github.com/magefan/module-blog/blob/master/etc/webapi.xml . Here you can find examples for curls in comments.
Also you can look at this file https://github.com/magefan/module-blog/blob/master/Model/PostManagement.php to understand how post list work for webapi.

E.G.:
- If you want get posts from blog main page in store view 1, with page 2, and limit 15
curl "http://mystore.com/index.php/rest/V1/blog/post/list/index/index/1/2/15"
- If you want to load one post with id 1 in store view 2 please try this
curl "http://mystore.com/index.php/rest/V1/blog/post/view/1/2"
