### ISSUE TITLE
View blog categories and posts as autonomous sections

### ISSUE THREAD

**Issue by gmvoliveira** [magefan/module-blog#64]
We use the blog to show different kinds of content on our webpage. We have two kinds of categories: **News** and **Reviews**. We want to have them appear to be autonomous sections. Trying to get this to work we came across some problems.

1. The **recent posts** in the sidebar always shows all recent posts, but we'd like to only show **recent posts** from the category that is active at that moment (when viewing a certain category or when viewing a post in a certain category). Is this possible, and if not would it be possible with an override of the ../sidebar/recent.phtml?

2. When viewing a category, the breadcrumbs show the correct path. So when viewing **News** the breadcrumbs show **Home > News**. When viewing a post though, the breadcrumbs don't show the category in the breadcrumbs, it shows **Home > Post Title** instead of **Home > News > Post Title** . Again: is this possible or do we have to override breadcrumb-files for this to be possible?

**Comment by magefan** [comment]
Hello @gmvoliveira 
1. You need to create custom module and override block Block/Sidebar/Recent.php you can also take a look at Block/Post/PostList/AbstractList.php
2. You need to override Block/Post/View.php
