### ISSUE TITLE
Blog comments without 3th party (fb / google etc)

### ISSUE THREAD

**Issue by GeoffreyDijkstra** [magefan/module-blog#66]
Q: Why is it not possible to add comments through a text field, with logged in M2 user? Current backend options are only disabled / google / disqus / facebook or am I missing something?

If it is not supported yet then I like to make a feature request.

**Comment by magefan** [comment]
@GeoffreyDijkstra, for now our blog extension support only google / disqus / facebook  comments. Build in magento comments will be available in next releases. If you require this feature right now, please contact us using email support@magefan.com

**Comment by GeoffreyDijkstra** [comment]
Hello @magefan, thx for the reply. Can you give an indication when this will be available?

**Comment by magefan** [comment]
@GeoffreyDijkstra I think it will be in a 3-4 month.

**Comment by tjsteinhaus** [comment]
Is this coming anytime soon?

**Comment by magefan** [comment]
We have a very good news :-) Built in comments functionality included in the new release v2.6.0. You can download it from our website https://magefan.com/magento2-blog-extension or via composer.

**Comment by GeoffreyDijkstra** [comment]
Awesome, thx man! 👍
