### ISSUE TITLE
Magento EE compatibility

### ISSUE THREAD

**Issue by nuzil** [magefan/module-blog#67]
Hello

Thanks a lot for those extenison, its looks great.
But unfortunately its not Magento EE compatible. 

And in detailed: 

As for extended admin rights management features, they are available only in Magento 2 Enterprise Edition. Thus, the separation of user roles in the admin panel is unique to EE. 

Thanks

**Comment by magefan** [comment]
Hello @nuzil  thank your for you report. We will check and try to fix this as soon as possible.

**Comment by magefan** [comment]
@nuzil , please upload this file (https://github.com/magefan/module-blog/commit/89642b595c303906b30c4d7fda80b3de1a4568e1) and put into your M2 blog directory. Then flush M2 cache. Please let us know if this works for you.

**Comment by magefan** [comment]
@nuzil  please confirm that fix is working for you.
