### ISSUE TITLE
Feature | Excerpt field for list view

### ISSUE THREAD

**Issue by rikwillems** [magefan/module-blog#69]
Currently the entire post content is shown on the list view. An excerpt field would be excellent to differentiate the content on the list and detail page.

**Comment by magefan** [comment]
@rikwillems please read this [article](https://magefan.com/blog/add-read-more-tag-to-blog-post-content/) to learn how to define short content.

**Comment by rikwillems** [comment]
@magefan this does create a shorter text as intro but it is only the start of the original article. This is not an excerpt or 'marketing' introduction to the article. I now used the meta_description field on the blog list to solve my wish. Does this clarify my use-case?
