### ISSUE TITLE
Support for enabling security keys in urls

### ISSUE THREAD

**Issue by ashsmith** [magefan/module-blog#70]
I've come across a strange issue whereby the store I'm working on (2.1.0 currently) required the security keys in admin urls to be removed in order to use your extension, which in light of a security issue raised before the weekend this is obviously a big no no. After a little investigation I found out why. All the action routes defined in menu.xml have a trailing slash `/`. Not sure why, but Magento doesn't like it! Removing them means the links work as expected and there is no broken functionality.

So the fix to my issue is dead simple in `etc/adminhtml/menu.xml` all of the defined actions need to the trailing `/` removed.

i.e.

```
action="blog/post/"
# becomes:
action="blog/post"
```

Happy to submit a PR.

Thanks

**Comment by magefan** [comment]
@ashsmith, thank you for your report, we have made required changes (https://github.com/magefan/module-blog/commit/9ad86ff2e944abb7cb2480aea27c477257e54848)
