### ISSUE TITLE
Cache management

### ISSUE THREAD

**Issue by Szymon-GP** [magefan/module-blog#71]
When i'm adding new categories they won't appear on the frontend until the cache is refreshed. Could it be due to my setup?

Magento CE ver. 2.1.4
Blog v.2.2.4

Cache status:
```
config: 1
layout: 1
block_html: 1
collections: 1
reflection: 1
db_ddl: 1
eav: 1
customer_notification: 1
full_page: 1
config_integration: 1
config_integration_api: 1
translate: 1
config_webservice: 1
```

**Comment by magefan** [comment]
@Szymon-GP , it is a standard Magento behavior, category would not show up until Block Cache and Page Cache will not be refreshed. Magento caching system improve performance. If you are making very active blog or cms editing, please temporary disable those caches.
