### ISSUE TITLE
Issue #7 not fixed. I can't delete related products and related posts

### ISSUE THREAD

**Issue by janbuelens** [magefan/module-blog#73]
Magento version: EE2.1.6
Module version: 2.5.0

I can add related products and related posts. The remove functionality doesn't work.
I checked the database and the related products are after a remove still present in the table magefan_blog_post_relatedproduct

**Comment by magefan** [comment]
@janbuelens, thank you for you report. Could you please try to use this fix (https://github.com/magefan/module-blog/commit/b65134cbf341a6807b9b09e6b655cc42dbbf2919). Please let us know if it works for you.

**Comment by janbuelens** [comment]
@magefan, the patch works, Thanks!
