### ISSUE TITLE
Lazy Loading with Auto Trigger DOESN'T work

### ISSUE THREAD

**Issue by Omi0** [magefan/module-blog#75]
If you use  configuration: Use Lazy Loading: Yes (With Auto Trigger)

It will not init at the right time. In order to fix it the following line of the code must be amended.
File: /view/frontend/web/js/lazyload.js
Line 89
From: if ($w.scrollTop() + $w.height() >= $(document).height() - that.opt.padding)  {
To: if ($w.scrollTop() + $w.height() >= $(that.opt.trigger_element).offset().top - that.opt.padding)  {

**Comment by magefan** [comment]
@Omi0 , thank you for contribution. Changes added https://github.com/magefan/module-blog/commit/cec5a58864414a00817a268b66589ab4e43d3119
