### ISSUE TITLE
Multi store Support.

### ISSUE THREAD

**Issue by dankocrama980** [magefan/module-blog#80]
Hello i would like to know if there is multi store support like as products,
so we can change the content of the article depending on the store view,
so that one blog post can be in EN and on in FR for example ?

![multistore](https://user-images.githubusercontent.com/974322/27732770-3e34d5ce-5d93-11e7-96d0-f6fda0f9baec.png)

**Comment by magefan** [comment]
Hello @dankocrama980 for this purpose you need to create 2 separate posts, one for EN and other for FR. They need to have identical identifier. It is the same behavior as with multilanguage for Magento CMS Pages

**Comment by dankocrama980** [comment]
OK cool Thanks for the reply 👍
