### ISSUE TITLE
Resize blog post images

### ISSUE THREAD

**Issue by Koc** [magefan/module-blog#81]
For now post images embedded in original resolution for view/list pages. Please add possibility to resize they like product images.

**Comment by magefan** [comment]
You can always override blog template and set diminutions you wish. Please read this article to learn how to resize blog post images
https://github.com/magefan/module-blog/wiki/How-to-resize-post-image-in-Magefan-Blog-extension-for-Magento-2

**Comment by Koc** [comment]
Thank you. Also online documentation url follows 404

**Comment by coughsyrupgit** [comment]
The example in the article on wiki doesn't work in version 2.5.3. The part `$imageHelper->init($_post->getFeaturedImg())->resize($width, $height);` doesn't return the resized image URL as expected. Nothing about this in logs also.
