### ISSUE TITLE
Rewrite not working

### ISSUE THREAD

**Issue by rbostan** [magefan/module-blog#84]
Hello, thanks for this great extension. 👍 

I've installed that successfully and accessible in '/blog' path.
But when i tried to access `/blog/hello-world.html` or `/blog/post/hello-world/` or `/blog/category/....` it redirects to 404 page.

Is it a rewrite bug or a configuration mistake ?

**Comment by magefan** [comment]
@rbostan 
1. What version of Magento extension do you use?
2. What version of Blog extension do you use (or you are using master tag code)?
3. Have you setuped web-server rewrites?
4. Maybe it's conflict with third party extension, try to find extension that use router blog. Look at routes.xml files for "blog" string

**Comment by rbostan** [comment]
1. Magento 2.1.2 (for now)
2. Blog 2.5.1
3. Yes, we are using rewrites on all website including blog.
3. No. There is not any extension which using 'blog' route.

Thank you.

**Comment by magefan** [comment]
@rbostan , we cannot replicate this issue on our test envelopment. Could you please contact our support https://magefan.com/contact and provide ssh and admin panel credentials?
