### ISSUE TITLE
Problem changing the layout in the category page

### ISSUE THREAD

**Issue by oabreu** [magefan/module-blog#86]
Hi,great extension! But we have a problem changing the layout of the category page,is always one column without left nav,so please let us know what can we do to change the layout of this page since adding layout attr is not working as it should be,thanks
File: blog_category_view.xml
<page layout="2columns-left" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd" >
    <update handle="blog_default"/>
    <update handle="blog_post_list"/>
    <body>
        <referenceContainer name="content">
            <block class="Magefan\Blog\Block\Category\Info" name="blog.posts.info" template="Magefan_Blog::category/info.phtml" before="blog.posts.list"/>
            <block class="Magefan\Blog\Block\Category\View" name="blog.posts.list" template="post/list.phtml"/>
        </referenceContainer>
    </body>
</page>

**Comment by magefan** [comment]
@oabreu have you tried to change category layout in blog category stetting?
Please navigate to M2 Admin Panel > Content > Blog > Categories > choose category > Design section 
 and change Layout filed to "2 columns with left bar" for example (don't forget to flush cache).

**Comment by oabreu** [comment]
thank you for answering so quick guys, and yes,that solved my problem,you are the best :) thanks
