### ISSUE TITLE
New post doesn't show on blog listing page due to Varnish FPC

### ISSUE THREAD

**Issue by erikhansen** [magefan/module-blog#87]
# Issue: 
When adding a new blog post, the Varnish FPC cache for the /blog page is not invalidated, so the blog post doesn't show for 24 hours.

# Steps to reproduce:

1. Install this extension on a Magento site that is configured with Varnish.
2. Load the /blog page multiple times to ensure it is cached in Varnish
3. Add a new blog post.

# Expected result:
* New blog post will show on the /blog page

# Actual result:
* New blog post will not show.
* If you add a random query string parameter to the /blog page (e..g, `/blog?bypassvarnish=true`), Varnish won't have that page cached, so the blog post _will_ show.

**Comment by magefan** [comment]
This feature is not present in our magento 2 blog extension. You can reproduce the same behavior on built-in (default) magento page cache.
We have added auto cache clean up backlog.
Thank you for the detailed report.
