### ISSUE TITLE
Sitemap Generation on divided sitemaps

### ISSUE THREAD

**Issue by BerMedia** [magefan/module-blog#93]
Magento Version: M2.1.9
Magefan Blog Version: 2.5.3

On Sitemap processing the first magento "sitemap-1-1.xml" is missing. After i comment out the blog sitemap generation plugin in the di.xml - everything is right.
 
![sitemap_missing](https://user-images.githubusercontent.com/15903912/31583597-e62f5e5c-b19e-11e7-96ad-09824d737efd.jpg)

**Comment by magefan** [comment]
@BerMedia could you please contact us via contact form https://magefan.com/contact and provide ssh and admin panel credentials so we can check and fix this issue?
