### ISSUE TITLE
Main blog page is not loading rest of site

### ISSUE THREAD

**Issue by charlottedrake** [magefan/module-blog#94]
Hi, 

The category and single post pages are loading fine, but the main blog page and archive pages are not loading the rest of the site. 

See screenshot:

![image](https://user-images.githubusercontent.com/26929758/31762709-f94e717c-b4b3-11e7-87e6-609a9105eed4.png)

There are no errors in the console. A lot of the scripts on not being loaded when I view page source.

**Comment by magefan** [comment]
What blog extension and theme do you use?

**Comment by charlottedrake** [comment]
https://magefan.com/magento2-blog-extension

Custom theme

**Comment by magefan** [comment]
oh.. I'm sorry... 
What blog extension version do you use.

**Comment by charlottedrake** [comment]
Blog Extension v2.5.3 was developed by MageFan.

**Comment by magefan** [comment]
Issue is fixed. It was related to third-party extension that cause the problem.
