### ISSUE TITLE
Error on setup:di:compile command

### ISSUE THREAD

**Issue by mihaelacmihai** [magefan/module-blog#95]
Hello,
I'm receiving an error when I try to install the blog on Magento 2.1.6 Community edition. It says: Compilation was started.
Repositories code generation... 1/7 [====>-----------------------]  14% 1 sec 46.0 MiB
Fatal error: Interface 'Magefan\Blog\Api\ManagementInterface' not found in /var/www/html/app/code/Magefun/Blog/Api/CategoryManagementInterface.php on line 11.
Could you please help? Thanks!

Regards,
Mihaela

**Comment by magefan** [comment]
@manfrinm maybe you had an issue during file upload to your server. Please check if this file https://github.com/magefan/module-blog/blob/master/Api/ManagementInterface.php present in blog extension folder on the server.

**Comment by mihaelacmihai** [comment]
Thank you for your response. Physically the file exists and has the right content.

**Comment by magefan** [comment]
@mihaelacmihai I think it's something specific to your magento instant. Could you please contact us via contact form https://magefan.com/contact and provide credentials so we can check?

**Comment by magefan** [comment]
as a suggestion try to remove var/di folder in your M2 directory

**Comment by mihaelacmihai** [comment]
Huray! thank you very much! the file permissions must have been the problem because now is working!
Best regards and congratulations! Great job with the blog extension, works like a charm!
