### ISSUE TITLE
Add Import Logging To A File

### ISSUE THREAD

**Issue by matthewscalf** [magefan/module-blog#96]
What would be awesome on the import is to have it log to a specific file so you can go track the issues down. I would love to see that, like yesterday :)

**Comment by magefan** [comment]
Hello @matthewscalf , thank you for suggestion. Please try to use this changes (https://github.com/magefan/module-blog/commit/2e94d884d36fc15576b3a8d1e3caea5d54c54946) they will be included in next version.
