### ISSUE TITLE
Magento 2.2 Issues

### ISSUE THREAD

**Issue by matthewscalf** [magefan/module-blog#98]
In magento 2.2 there are issues with this file:

view/adminhtml/layout/blog_import_index.xml

<block class="\Magento\Backend\Block\Template" name="blog.import" template="Magefan_Blog::import.phtml" />

should be

<block class="Magento\Backend\Block\Template" name="blog.import" template="Magefan_Blog::import.phtml" />

**Comment by magefan** [comment]
@matthewscalf, yes you are right, please try this fix https://github.com/magefan/module-blog/commit/0568816699f6eec4e3d3302d4fa329b95fd96a79

**Comment by matthewscalf** [comment]
I manually applied it in my dev obviously and it worked but I would love a clean composer update so I can easily deploy this to the entire production cluster.

**Comment by danslo** [comment]
@matthewscalf Pro tip: you can temporarily use composer version ``dev-master#0568816`` until a new release is drafted.

**Comment by magefan** [comment]
New release will be available in 1-2 weeks.
